### ISSUE TITLE
COTD scripting progress

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#109]
Now that [the list has been released](http://blog.livedoor.jp/maxut/archives/49857041.html), I'm preparing the topic in advance. I'll keep updating it once new info come out.

- [x] COTD-JP012 - Hack Worm --ハック・ワーム
- [x] COTD-JP013 - Jack Wyvern --ジャック・ワイバーン
- [x] COTD-JP014 - Cracking Dragon --クラッキング・ドラゴン
- [x] COTD-JP015 - Supreme King Servant Dragon Odd-Eyes --覇王眷竜オッドアイズ
- [x] COTD-JP016 - Predaplant Banksia Ogre --捕食植物バンクシアオーガ
- [x] COTD-JP032 - Treasure Pander --トレジャー・パンダー
- [x] COTD-JP033 - Zombiena --ゾンビーナ
- [x] COTD-JP036 - Kaminari Senjin --雷仙神
- [x] COTD-JP037 - Parry Knight --パーリィナイツ
- [x] COTD-JP041 - Supreme King Servant Dragon Dark Rebellion --覇王眷竜ダーク・リベリオン
- [x] COTD-JP046 - Topologic Bomber Dragon --トポロジック・ボマー・ドラゴン
- [x] COTD-JP055 - Aircrack Storm --エアークラック・ストーム
- [x] COTD-JP056 - Smile Universe --スマイル・ユニバース
- [x] COTD-JP062 - Spellbook of Rudra --ルドラの魔導書
- [x] COTD-JP063 - Sluggishness --鈍重
- [x] COTD-JP066 - Defense Zone --ディフェンスゾーン
- [x] COTD-JP069 - Pulse Bomb --パルス・ボム
- [x] COTD-JP070 - Supreme King's Wrath --覇王の逆鱗
- [x] COTD-JP073 - Twilight Cloth --黄昏の交衣
- [x] COTD-JP078 - Recall --無償交換
- [x] COTD-JP079 - Blind Ruination --無差別崩壊
- [x] COTD-JP080 - Transmission Gear --変則ギア

**Comment by EerieCode** [comment]
Now that we have most of the cards, I think there might be an issue with 080. Do we _have_ a function that lets you play Rock-Paper-Scissors with your opponent during the game? I know we have one at the start of the game, but I don't know if it can be called by a script.

**Comment by EerieCode** [comment]
@Hello23-Ygopro Any particular reason for that dislike above? You know, I've seen you put a dislike on almost every issue I open here, but I haven't seen any _reason_ for it yet...

**Comment by AndreOliveiraMendes** [comment]
the reason is cause he a troll? ~~or racist?~~
