### ISSUE TITLE
CP17 Rulings

### ISSUE THREAD

**Issue by TheOnePharaoh** [Fluorohydride/ygopro-pre-script#119]
https://ygorganization.com/ocg-collectors-pack-2017-rulings/

- [x] If a face-down Pendulum Monster in your Monster Zone is attacked by an opponent’s monster, flipped face-up, and destroyed, you can activate the effect of an Odd-Eyes Lancer Dragon in your hand that Special Summons it. Also, if a face-down Pendulum Monster in your Monster Zone is destroyed by a card effect such as Shield Crush, you cannot activate the effect of an Odd-Eyes Lancer Dragon in your hand that Special Summons it.

- [ ] when Mystical Space Typhoon destroys the only Set card in your Spell & Trap Zone, you will have no Set cards, so the effect of Performapal Five-Rainbow Magician that prevents monsters on your field from attacking or activating their effects applies. In that case, the attack of Odd-Eyes Wing Dragon stops. (Damage calculation is not performed.)

- [ ]  when resolving the monster effect of D/D/D Superdoom King Whitest Armageddon, there are no face-up Pendulum Monsters on your opponent’s field. In that case, the effect is not applied. (The effects of Odd-Eyes Lancer Dragon are not negated.)

- [ ] A: If White Moray is Normal Summoned while the effect of Skill Drain is applying, White Moray cannot attack directly this turn with its own effect, even if the effect of Skill Drain later stops applying. Also, if Skill Drain is activated after White Moray is Normal Summoned, White Moray can still attack directly that turn with its effect. `though personally I think that's a bit strange`

- [ ] Even if Amazoness Pet Liger attacks and is destroyed by battle, you can activate its effect after damage calculation.

- [ ] Even if you cannot Special Summon with the effect of Monster Reborn because the targeted monster is no longer in the Graveyard, since Monster Reborn was still activated successfully, the effect of Quiet Life is applied and you cannot Normal Summon for the rest of this turn.

- [ ] Q: Quiet Life is face-up in the Spell & Trap Zone. In this situation, I Special Summon a Dogoran, the Mad Flame Kaiju from my hand to my opponent’s field with its effect. In this case, which player will the effect of Quiet Life be applied to?
 A: In this scenario, the player who Special Summoned Dogoran, the Mad Flame Kaiju is the one who cannot Normal Summon during this turn due to the effect of Quiet Life. (The effect is not applied to your opponent, whose field Dogoran, the Mad Flame Kaiju was Special Summoned to.)

- [ ] If a Vision HERO Witch Raider in your hand is treated as a Level 6 monster by the effect of Cost Down, you can then Tribute Summon it by Tributing 1 Trap Card instead of a monster.

- [ ]  You cannot activate the effect of Vision HERO Witch Raider during the turn you Special Summon a monster in face-down Defense Position. (Even if the monster that you Special Summoned in face-down Defense Position was a “HERO” monster, you cannot activate the effect of Vision HERO Witch Raider.)

- [x] Even if there are no cards in your opponent’s Graveyard, if your Lazion, the Timelord battled during this Battle Phase, its effect will activate and start a Chain.

- [x] Q: My Sadion, the Timelord battled during the current Battle Phase. During the End Step of this Battle Phase, my Life Points are 3500, so the effect of Sadion, the Timelord that makes my Life Points become 4000 activates. My opponent chains Smile Universe and Special Summons Odd-Eyes Pendulum Dragon, so that I also gain 2500 Life Points, and they become 6000. In this case, how does the effect of Sadion, the Timelord resolve?
 A: As in this scenario, if your Life Points are higher than 4000 when the effect of Sadion, the Timelord resolves, the effect will still make your Life Points become 4000.

those are the ones that I thought may need script fixes.

**Comment by TheOnePharaoh** [comment]
https://github.com/TheOnePharaoh/ygopro-pre-script/tree/CP-17Rulings
Lancer Dragon Fix bd48c79ac2b978f3bf961b689d87cf26d90ec31b

**Comment by TheOnePharaoh** [comment]
I'll post all the fixes I make here
https://github.com/TheOnePharaoh/ygopro-pre-script/tree/CP-17Rulings

**Comment by nekrozar** [comment]
> when resolving the monster effect of D/D/D Superdoom King Whitest Armageddon, there are no face-up Pendulum Monsters on your opponent’s field. In that case, the effect is not applied. (The effects of Odd-Eyes Lancer Dragon are not negated.)

In Data Base, if opponent has no Pendulum Monster, _D/D/D Superdoom King Whitest Armageddon_'s effect don't apply.
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=20978&keyword=&tag=-1
> Q.相手がペンデュラム召喚によって、手札から「オッドアイズ・ペンデュラム・ドラゴン」と「オッドアイズ・ランサー・ドラゴン」を特殊召喚した際に、自分は「DDD超死偉王ホワイテスト・ヘル・アーマゲドン」の『②：このカードが既にモンスターゾーンに存在する状態で、このカード以外のモンスターが召喚・特殊召喚された場合に発動できる。相手は自身のフィールドのPモンスター１体を選ぶ。そのモンスター以外の相手フィールドのモンスターの効果は無効化される』モンスター効果を発動しました。
> 
> その発動にチェーンして、相手が「月の書」を発動し、「オッドアイズ・ペンデュラム・ドラゴン」を裏側守備表示にした場合、「DDD超死偉王ホワイテスト・ヘル・アーマゲドン」のモンスター効果の処理はどうなりますか？
> A.質問の状況の場合、「DDD超死偉王ホワイテスト・ヘル・アーマゲドン」の『相手は自身のフィールドのPモンスター１体を選ぶ。そのモンスター以外の相手フィールドのモンスターの効果は無効化される』モンスター効果の処理時に、相手のモンスターゾーンには表側表示のペンデュラムモンスターが1体も存在しない状態となっています。
> 
> この場合には、**「DDD超死偉王ホワイテスト・ヘル・アーマゲドン」のモンスター効果は適用されません**。
> （**相手のモンスターゾーンに表側表示で存在する「オッドアイズ・ランサー・ドラゴン」のモンスター効果が無効化される事はありません。**）

**Comment by TheOnePharaoh** [comment]
working on it
