### ISSUE TITLE
May 2017 VJump cards

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#121]
**Circuit Break** (101002XXX)
- [x] 007 - Gateway Dragon
- [x] 008 - Sniffing Dragon
- [x] 009 - Anesvullet Dragon
- [x] 010 - Autovullet Dragon
- [x] 011 - Magnavullet Dragon
- [x] 023 - Metaphys Ragnarok
- [x] 024 - Metaphys Daedalus
- [x] 025 - Metaphys Nephthys
- [x] 026 - Metaphys Tyrant Dragon
- [x] 042 - Varrel Lord Dragon
- [x] 046 - Twin Triangle Dragon
- [x] 051 - Akashic Magician
- [x] 055 - Squib Draw
- [x] 056 - Quick Revolve
- [x] 059 - Metaphys Factor
- [x] 075 - Metaphys Dimension

**Structure Deck: Cyberse Link** (100332XXX)
- [x] 003 - Kleinant
- [x] 004 - Backlinker
- [x] 007 - Boot Stagguard
- [x] 023 - Cybnet Backdoor
- [x] 041 - Encode Talker

**Duelist Pack: Legend Duelist** (100418XXX)
- [x] 022 - Cyberdark Cannon
- [x] 023 - Cyberdark Claw
- [x] 025 - Cyberdark Inferno
- [x] 029 - Mixeroid
- [x] 031 - Megaroid City
- [x] 037 - Deuterion
- [x] 038 - Bonding - D2O
- [x] 039 - Bonding - DHO

**Promos** (100200XXX)
- [x] 134 - White Stingray
- [x] 135 - D/D/D Supersight King Zero Maxwell

**Comment by edo9300** [comment]
Varrel Lord Dragon needs a core update for the last effect to be fully implemented, this script https://github.com/Fluorohydride/ygopro-pre-script/commit/085ab5727f2e67721a3b051c9ecc72040cb9fa31 is a temporairy version and to work will require this function to be added https://github.com/Fluorohydride/ygopro-core/pull/94, the possibility to specify a zone for the control change, without using the selectdisablefield function, also there's a problem that have to be investigated, atm when you switch the control of a monster at the start of the damage step, the attack continues, even if the control changed, so if this is revealed to be wrong then a fix will be required

**Comment by destdev** [comment]
about the cyberdark spells/traps, we may need to introduce another archtype for those
a user just brought up something on our forums
https://ygodevpro.com/forum/showthread.php?tid=994&pid=2153#pid2153
in short:
compare the name of cyberdark monsters and cyberdark s/t we have a slight difference
サイバー・ダーク
サイバーダーク
what do you think, do I see that correctly or do I miss something?

**Comment by mercury233** [comment]
Yes they are different but I think we should treat them as the same, like 「融合」/「フュージョン」, until konami distinguish them.
