### ISSUE TITLE
Scripting the Weathery cards

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#133]
Two of the latest Weathery cards, "[Rainbow Weathery Arciel](http://yugioh.wikia.com/wiki/Rainbow_Weathery_Arciel)" and "[Rain Weathery Condition](http://yugioh.wikia.com/wiki/Rain_Weathery_Condition)", haven't been scripted yet: the reason for that is because of their unprecedented effects, that grant effects to monsters on the field depending on their position relative to it (Arciel can give effects to monsters it points to, while Condition gives it to monsters in adjacent columns). It _might_ be possible to script these effects by using EVENT_ADJUST, but it's an unelegant method that will most definitely cause some issues: as such, I think we need to update the core with a way to have a card grant a particular effect to other cards as long as certain conditions are respected. Conceptually, the closest thing we have at the moment is the EFFECT_TYPE_XMATERIAL of the Zoodiacs, though I don't know how difficult it would be to script it so that it works on multiple monsters. Any thoughts, or alternative ideas for these cards?

**Comment by EerieCode** [comment]
I've added a prototype for the Weathery cards I mentioned, plus the "Thunder Weathery Pattern" I mentioned. They seemed to work in a puzzle, but I don't know what kind of issues could arise in a more complex scenario: also speaking of complexity, it's easy to see from the script how impractical repeating this on multiple cards would be. So, in conclusion, while cards with these kinds of effects are technically implementable purely in .lua, I'd still recommend looking for a better, simpler and more stable alternative.

**Comment by mercury233** [comment]
My ideal way:
> EFFECT_TYPE_AURA		=0x2000		--光环类效果（天气）

> int Card.GetColumn(Card c)
_return the absolute column sequence of card `c`_

> bool Card.IsInColumn(Card c, int col[, int l, int r])
_return if the card `c` is placed in the column `col`  [or in the column left side by `l` or right side by `r`]_

```lua
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(100419037,0))
	e1:SetCategory(CATEGORY_TOHAND)
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCondition(nil)
	e1:SetCost(aux.bfgcost)
	e1:SetTarget(c100419037.thtg)
	e1:SetOperation(c100419037.thop)
	--get effect
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_AURA)
	e2:SetRange(LOCATION_SZONE)
	e2:SetCondition(nil)
	e2:SetTarget(c100419037.auratg)
	e2:SetTargetRange(LOCATION_MZONE,0)
	e2:SetLabelObject(e1)
	c:RegisterEffect(e2)

function c100419037.auratg(e,c)
	return c:IsInColumn(e:GetHandler():GetColumn(),1,1)
		and c:GetSequence()<5 and c:IsFaceup() and c:IsType(TYPE_EFFECT) and c:IsSetCard(0x207)
end
```

And I guess we can temporally implement `EFFECT_TYPE_AURA` in lua.

**Comment by edo9300** [comment]
@mercury233 hmm I think that could be a good idea, now it only remains to add that in the core xD

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-core/pull/100
https://github.com/Fluorohydride/ygopro-core/pull/100/commits/0d1b025ed379b941ea4321baa386c17d9f059e60
@mercury233 Update `Card.GetColumnGroup`.
So, it might be a good idea to use this.
```
function c100419037.auratg(e,c)
	return e:GetHandler():GetColumnGroup(1,1,false):IsContains(c)
		and c:IsFaceup() and c:IsType(TYPE_EFFECT) and c:IsSetCard(0x207)
end
```

**Comment by edo9300** [comment]
@mercury233 but there could be a problem, in that way, the owner of the monster will be able to use the effect too

**Comment by mercury233** [comment]
@edo9300 The effect is not actually registered to the card itself. I guess it will work.

**Comment by EerieCode** [comment]
@edo9300 Adding ```and e:GetHandler()~=c``` should be enough to solve the issue. I agree with nekrozar, using GetColumnGroup is a good idea.
