### ISSUE TITLE
July VJump

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#136]
**Deck Build Pack: Spirit Warriors (100419XXX)**

- [x] 017: Magibullet Shooter Doctor --魔弾の射手 ドクトル
- [x] 019: Magibullet Shooter Starr --魔弾の射手 スター
- [x] 024: Magibullet - Cross-Dominator --魔弾－クロス・ドミネーター
- [x] 027: Magibullet - Devil's Deal --魔弾－デビルズ・ディール
- [x] 029: Snow Weathery Ciel --雪天気シエル
- [x] 038: Cloudy Weathery Pattern --曇りの天気模様
- [x] 041: Aurora Weathery Pattern --オーロラの天気模様

**Extra Pack 2017 (100420XXX)**

- [x] 001: Subterror Behemoth Apparition --サブテラーマリスの妖魔
- [x] 018: SPYRAL - The Double Helix --ＳＰＹＲＡＬ－ザ・ダブルヘリックス

**Structure Deck R: Surge of Divine Light (100305XXX)**

- [x] 001: Arch-Parshath, the Noble Airknight --天空聖騎士アークパーシアス

**Comment by EerieCode** [comment]
So, what number should we use for the Extra Pack? I don't think we've ever had to script cards from an Extra Pack before...

**Comment by mercury233** [comment]
The omnipotent `10020x00x`

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/991049a943758bc91083f940ae9dbbc30c8e025f Sorry, I updated sets.md...

**Comment by EerieCode** [comment]
It shouldn't be a problem, as long as we have a number. 100420XXX should be fine

**Comment by EerieCode** [comment]
All cards have been added, and it seems this is all we're going to get. I'm closing the issue.
