### ISSUE TITLE
Potential issue with "Magical Boost"

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#137]
There might be an issue requiring either a core update or a script overhaul in the new card "[Magical Boost](http://yugioh.wikia.com/wiki/Magical_Boost)", this part specifically:
_You can Special Summon **1 monster from your Deck that you can place a Spell Counter on**, and if you do, place 2 Spell Counters on it._
I'm almost certain Card.IsCanAddCounter doesn't work on cards not on the field, and as far as I know there's no function that lets you access the counter permits outside of that: as such, I can only think of 3 possible solutions:
1. We add a line in all scripts of cards that can use Spell Counters, like it was done with cards with "Dark Magician" in their card text: something like c101003022.spell_counter_permit=true. Note: following the edit below, this solution would, instead of a boolean, set the maximum number of counters, or 99 for cards with no limit.
2. We edit Card.EnableCounterPermit so that it also sets a flag on that card, and then cards like "Magical Boost" will check if that flag has been set. This could theoretically be done directly through .lua, though it's hardly an elegant solution. Note: in light of the edit below, the flag effect description could contain the maximum number for cards with a limit, allowing to check that as well.
3. We add a function to the core that lets you check the counter permits regardless of location, allowing us to identify the cards affectable by this effect.

What do you think? Does anyone have an alternative solution?

**EDIT:** Important note to consider: since this effect is supposed to place 2 Spell Counters, any solution we use also requires a way to check the maximum number of counters. As such, I'll add this 4th solution:
4. Edit Card.IsCanAddCounter with an extra flag that will force it to ignore the current location of the card: instead of checking whether you can place a counter in that exact moment, it will just check permit and maximum number of counters.

**Comment by EerieCode** [comment]
I've uploaded a temporary version of "Magical Boost" based on solution 1, with all valid cards hardcoded in it: the other Mythical Beast cards have also been altered to fit said solution. It should allow us to test for bugs while we decide the best solution.

**Comment by ClementLouis** [comment]
@Hello23-Ygopro I noticed that you give a lot of thumb down to some issues/post (mostly the ones from Eerie)
There is a reason for that? Because you never explain anything
It just look weird, most of the time there is only 1 thumb down, the one you put
and I don't think you missunderstand the meaning given that sometime you put a thumb up on other post (like mercury)

**Comment by EerieCode** [comment]
Not to mention that you never give a _reason_ for them. I wouldn't mind if you did, I always welcome constructive criticism, but when you only put thumbdowns without ever explaining yourself it looks less like "disagreement" and a lot more like "spite"...

**Comment by Zayelion** [comment]
I suggest option 3.

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/95f4e8bd127b3b974aec60d2f3af70e111707fe0 Updated.
