### ISSUE TITLE
Time Maiden

### ISSUE THREAD

**Issue by amilorea** [Fluorohydride/ygopro-pre-script#139]
Hello, somebody told me you are the one who write the script for Time Maiden, and its seems like the script have a bug: Time Maiden cannot search Metaion, the Timelord despite of he matching the condition. I can search any other Timelord, except Metaion.  Sorry I dont know anywhere else to report bug, but if this is your responsibility, I hope you can fix the script as soon as possible. Have a good day, thank you.

**Comment by mercury233** [comment]
Which ygopro version is you using? It seems that the Metaion in your database didn't get added Timelord setcode.

**Comment by amilorea** [comment]
I am using YGOPro2 1033.D.4
Sorry for the late reply.

**Comment by nekrozar** [comment]
You should be report this bug to YGOPro2's creater team.
