### ISSUE TITLE
BUG: Magician of Black Illusion can active its 3rd effect eventhough is was destroyed

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro-pre-script#14]
ex: destroy my Magician of Black Illusion with Dark Hole, it will be able to active its effect in graveyard.
I don't know how to fix it.

**Comment by destdev** [comment]
just add a check for the location in the target function? ... at least that seems to work fine and no longer tries to activate if destroyed by the own dark hole

**Comment by mercury233** [comment]
Seems a good idea.
