### ISSUE TITLE
VJump - September 2017

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#140]
**Duelist Pack: Legend Duelist 2** (100407XXX)

- [x] 001: Millennium-Eyes Illusionist
- [x] 003: Millennium-Eyes Restrict
- [x] 004: Relinquished Fusion
- [x] 007: Parasite Paranoid
- [x] 008: Ultimately Mutated Insect Queen
- [x] 009: Super Cocoon of Evolution
- [x] 014: BM-4 Bomb Spider
- [x] 015: Desperado Barrel Dragon
- [x] 017: Gun Cannon Shot

**Extreme Force** (101003XXX)

- [x] 009: Tindangle Angel
- [x] 010: Tindangle Base Gardna
- [x] 011: Tindangle Hound
- [x] 012: Tindangle Apostle
- [x] 013: Tindangle Intruder
- [x] 014: Mekk-Knight of the Blue Sky
- [x] 015: Mekk-Knight of the Green Heights
- [x] 016: Mekk-Knight of the Flickering Flame
- [x] 017: Mekk-Knight of the Yellow Bloom
- [x] 018: Mekk-Knight of the Crimson Lotus
- [x] 020: Mekk-Knight of the Purple Dusk
- [x] 045: Tindangle Acute Cerberus
- [x] 047: Mekk-Knight of the World Remains
- [x] 054: Protected Sky of Nagel
- [x] 055: Euler Circuit
- [x] 056: Wounds Carved on the World Legacy
- [x] 057: Key to World Legacy
- [x] 069: Tindangle Dalaunay
- [x] 071: Whisper of the World Legacy
- [x] 072: Deep Depths of the World Legacy's Slumber

**PROMOS**

- [x] Odd-Eyes Revolution Dragon
- [x] White Aura Biphamet

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/5f67c18822546bb7182c9c5a6567d42ecfe7592d
@EerieCode I made this commit before I saw you used `c.coin_toss` ...

**Comment by EerieCode** [comment]
Didn't see that. Oh well, it's no big deal! I can simply change the new monster

**Comment by destdev** [comment]
not sure if that might be a translation issue, according the the current text on wikia Millennium-Eyes Restrict might also need a disable effect similar to Fabled Unicore / Royal Decree perhaps?
It doesn't restrict the place or the position of the monsters to be negated.

**Comment by EerieCode** [comment]
I'm not entirely sure: I'd need to check the original text just to be sure.
Speaking of errors, do you think we should change the IDs of the Duelist Pack cards? I noticed only now they've also been used by DBSW...

**Comment by mercury233** [comment]
I don't think DP19 should be changed since it is DBSW who used the wrong id, which should be 100407xxx.

**Comment by EerieCode** [comment]
Even if DBSW was the wrong one, at the moment we still have two unrelated
sets using the same range.

Il 16 set 2017 06:38, "Mercury233" <notifications@github.com> ha scritto:

**Comment by mercury233** [comment]
In my opinion: 
`100100xxx` : Preserved.
`1003xxxxx` : SD, SDR and YSD. SDR (such as SR05) is always minus than SD (such as SD32), and YSD (such as ST17) is always between them, so it will be ok.
`1004xxxxx` : DP, SP. SPFE is treated as SP6, and DBSW may be the continue of it, so it will be ok to put it under `10040axxx`.
`1002xxxxx` : Other. EP17 should be here too.

**Comment by EerieCode** [comment]
I see... So, for now we keep the numbers as they are?

**Comment by mercury233** [comment]
yes i suggest so

**Comment by EerieCode** [comment]
Ok. By the way, if no one else is doing it, I'm willing to script Odd-Eyes Revolution Dragon too. Is 100210002 fine for a number?

**Comment by StormWulf** [comment]
My complaint about reusing IDs for DP19 is that it makes it harder for ID deck fixer programs to work. I would suggest using a different convention for it.

**Comment by EerieCode** [comment]
@StormWulf Agreed: I didn't consider it, but many users rely on these programs to update their Decks, and having multiple IDs will make using them impossible. It's definitely best to update the IDs now, while there are only a few cards: if we wait later, it will just get even more complicated.

**Comment by EerieCode** [comment]
Closing now that all cards have been scripted.
