### ISSUE TITLE
October 2017 VJump and Extreme Force leaks

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#153]
**EXTREME FORCE**           101003XXX
- [x] 003: Striping Panther --ストライピング・パートナー
- [x] 004: Flick Clown --フリック・クラウン
- [x] 007: Metalrokket Dragon --メタルヴァレット・ドラゴン
- [x] 024: Mythical Beast Medusa --魔導獣 メデューサ
- [x] 025: Mythical Beast Basilisk --魔導獣 バジリスク
- [x] 029: Angrappler --屈強の釣り師
- [x] 030: Janshimatsu --雀姉妹
- [x] 033: Desmania Devil --デスマニア・デビル
- [x] 035: Inspect Boarder --インスペクト・ボーダー
- [x] 036: Overtex Coatls --オーバーテクス・ゴアトルス
- [x] 037: Contacting "C" --接触するＧ
- [x] 048: Skulldeat, the Chained Dracoserpent --鎖龍蛇－スカルデット
- [x] 051: Linkage Hole --リンケージ・ホール
- [x] 053: Revolve Boot Sector --リボルブート・セクター
- [x] 060: Power of the Guardian --ガーディアンの力
- [x] 062: Localized Trunade --局所的ハリケーン
- [x] 065: Role Reversal --身分転換
- [x] 068: Borrel Refrigeration --ヴァレル・レフリジェレーション
- [x] 076: Sensor Differentiation --センサー万別
- [x] 077: GUY Dance --ＧＵＹダンス
- [x] 079: Parthian Shot --一撃離脱
- [x] 080: --誤爆

**PROMOS**
- [x] 100200139: Security Dragon --セキュリティ・ドラゴン

**Structure Deck: Powercode Link**  100333XXX
- [x] 001: Dongle Acorn --ドングルドングリ
- [x] 031: Packet Link --パケットリンク
- [x] 040: Powercode Talker --パワーコード・トーカー

**LINK VRAINS Pack**  100223XXX
- [x] 006: Gladiator Beast Dragacius --剣闘獣ドラガシス
- [x] 011: Kyrios, Dominion of the Lightsworn --ライトロード・ドミニオン・キュリオス
- [x] 031: Hieratic Seal of the Celestial Spheres --天球の聖刻印
- [x] 061: Qliphort Genius --クリフォート・ゲニウス
- [x] 081: Cherubini, Black Angel of the Burning Abyss --彼岸の黒天使 ケルビーニ
- [x] 091: Crystron Halifiber --水晶機巧-ハリファイバー

**Duelist Pack: Legend Duelist 2**   100407XXX
- [x] 022: Ojamadification --おジャマ改造
- [x] 023: Ojamatching --おジャマッチング
- [x] 030: Ancient Gearframe --古代の機械素体

**Comment by nekrozar** [comment]
Maybe _Contacting "C"_ and _GUY Dance_ need new code.

**Comment by EerieCode** [comment]
Most likely: I left them on the list for completion's sake, but I'm 99% sure we'll need a core update for them.

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/176dfba0a3be823c02d473de0bdd9d2c4bf6c261 _GUY Dance_ added.
This problem has _Contacting "C"_ only.

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/bc023757cf907a820193fb5cb8ae1c9297c04ed8 _Contacting "C"_ added.
