### ISSUE TITLE
Issue Cynet Storm

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro-pre-script#156]
> https://yu-gi-oh.jp/index.php?page=details&&id=147
> ③：自分が２０００以上の戦闘・効果ダメージを受けた場合に発動できる。**自分のＥＸデッキの裏側表示のカードだけをシャッフルし**、その一番上のカードをめくる。めくったカードがサイバース族リンクモンスターだった場合、そのモンスターを特殊召喚する。違った場合は元に戻す。
> English Translation
> If you take 2000 or more damage by battle or a card effect: **You can shuffle the face-down cards in your Extra Deck** and excavate the top card of those cards, and if is a Cyberse Link Monster, Special Summon it. Otherwise, return it to its original position.

However, current version can't shuffle Extra Deck.
Do you have any good ideas?

**Comment by EerieCode** [comment]
Theoretically, we could make a pseudo-version by having the system randomly select a face-down card from the Extra Deck: the end result would basically simulate shuffling the ED and then picking the top card. It would just be a stop-gap, though, in the end we need a core update to allow shuffling of the Extra Deck.

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/74247b0dd884254a153062c2eada47264246cfbb This problem solved.
