### ISSUE TITLE
Flames of Destruction - Remaining cards

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#160]
- [x] 002: Prompt Horn --プロンプトホーン
- [x] 004: Link Streamer --リンク・ストリーマー
- [x] 005: Degrenade Buster --デグレネード・バスター
- [x] 014: Altergeist Multifaker --オルターガイスト・マルチフェイカー
- [x] 015: Altergeist Pixiel --オルターガイスト・ピクシール
- [x] 028: Watch Cat --番猫－ウォッチキャット
- [x] 029: Transfamiliar --トランスファミリア
- [x] 030: Outroll of the Haunted Sea --妖海のアウトロール
- [x] 031: Yajirovader --ヤジロベーダー
- [x] 033: Yashiki Warashi --屋敷わらし
- [x] 034: Rapid Red Hared Mare --急き兎馬
- [x] 035: Boycotton --ボイコットン
- [x] 040: Trickstar Delfiendium --トリックスター・デビルフィニウム
- [x] 051: Pint-Sized Priest Hidaruma --小法師ヒダルマー
- [x] 053: Cybersal Cyclone --サイバーサル・サイクロン
- [x] 055: Trickstar Bouquet --トリックスター・ブーケ
- [x] 057: World Legacy End --星遺物が導く果て
- [x] 059: World Legacy Nightmare --星遺物へ誘う悪夢
- [x] 062: Light of Sekka --雪花の光
- [x] 064: Staredown --にらみ合い
- [x] 065: Designator from the Grave --墓穴の指名者
- [x] 066: Selective Reborn --取捨蘇生
- [x] 067: Limit Code --リミット・コード
- [x] 070: Altergeist Emulelf --オルターガイスト・エミュレルフ
- [x] 071: World Legacy Awakening --星遺物からの目醒め
- [x] 073: World Legacy Echo --星遺物に響く残叫
- [x] 075: Darklord Divinity --神属の堕天使
- [x] 078: Ruthless Drop Off --無情なはたき落とし
- [x] 079: Mamemaki --豆まき
- [x] 080: Shrub Serpent --やぶ蛇

**Comment by Sun4Ever2** [comment]
Trickstar Bouquet have many issues in scripting? just  asking :3

**Comment by EerieCode** [comment]
Nothing in particular, I just hadn't had time to script it yet :P. I'll work on it in a moment.

**Comment by nekrozar** [comment]
Maybe _Rapid Red Hared Mare_ need `EVENT_TO_FIELD`...
Do you have any other good ideas?

**Comment by EerieCode** [comment]
Yesterday I was considering a combination of EVENT_ADJUST and flags. Basically, we have it set a flag on all cards on field when it's summoned, and then, whenever the game state changes, we have it check for cards that don't have the flag, meaning they're newly placed cards. If they're on the same column, then we destroy Mare. Honestly, though, that would end up causing all sorts of issues, in particular since it wouldn't work with 2 Mares on field simultaneously. I agree with you, we definitely need EVENT_TO_FIELD for a clean implementation.

**Comment by Sun4Ever2** [comment]
Yashiki Warashi does she have any problems at all I see she is the only one left after the last one to be added hmmm..
