### ISSUE TITLE
Maybe Problematic future effects

### ISSUE THREAD

**Issue by ClementLouis** [Fluorohydride/ygopro-pre-script#188]
I know that you prefer to wait for a cards being officialy announced to start to work on new effects
But I noticed 2 cards appearing in the anime that could result in a lot of problems
Both have great art, used by a major character (Revolver/Varis) that have cards released in 2 different boosters (Cybernetic Horizon and Collector Pack 18)
Also, Prohibition got a updated wording using a "cannot place" that is similar to one of the effect 

Those cards are 
- Flash Charge Dragon with a "You cannot place monsters in the zones this card points to. " effect
https://yugipedia.com/wiki/Flash_Charge_Dragon
- Voritcular Drumgon with the following effect: "While this card is face-up on the field, monsters cannot be Normal or Special Summoned to the zones this card points to during the turn this effect was activated (and was not negated)."
https://yugipedia.com/wiki/Voritcular_Drumgon

**Comment by ahtelel** [comment]
As of right now, Muzzleflash Dragon (Flash Charge Dragon) mentioned in the above issue has been revealed to be released in Collectors Pack 2018, with the same effect (You cannot place monsters in the zones this card points to.) I suggest we should, or at least begin to, come up with an effective solution for this issue.

**Comment by MichaelLawrenceDee** [comment]
@Hello23-Ygopro hey, calling you out since you keep thumbing down Percy staff, @ahtelel is one of us too.

**Comment by purerosefallen** [comment]
Thumb down again?
