### ISSUE TITLE
TDIL scripting progress

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro-pre-script#19]
- [x] TDIL-JP001	Performapal Bot-Eyes Lizard	ＥＭボットアイズ・リザード (100909101)
- [x] TDIL-JP002	Performapal Gongcat	ＥＭドラネコ
- [x] TDIL-JP003	Performapal Extra Shooter	ＥＭエクストラ・シューター
- [x] TDIL-JP004	Performapal Barrier Balloon Baku	ＥＭバリアバルーンバク
- [x] TDIL-JP005	Performapal Rubber Mutton	ＥＭゴムゴムートン 
- [x] TDIL-JP006	Performapal Bubbulldog	ＥＭバブルドッグ
- [x] TDIL-JP007	Performapal Radish Horse	ＥＭラディッシュ・ホース
- [x] TDIL-JP008	Performapal Life Swordsman	ＥＭライフ・ソードマン
- [x] TDIL-JP009	Acrobat Magician	曲芸の魔術師
- [x] TDIL-JP010	D/D Savant Thomas	ＤＤ魔導賢者トーマス
- [x] TDIL-JP011	D/D Savant Nikola	ＤＤ魔導賢者ニコラ
- [x] TDIL-JP012	Blackwing - Tornado the Raging Squall	ＢＦ－逆巻のトルネード
- [x] TDIL-JP013	Blackwing - Gofu the Hazy Shadow	ＢＦ－朧影のゴウフウ (100909102)
- [x] TDIL-JP014	Red Wolf	レッド・ウルフ
- [x] TDIL-JP015	Red Gardna	レッド・ガードナー 
- [x] TDIL-JP016	Red Mirror	レッド・ミラー
- [x] TDIL-JP017	Magician of Black Illusion	マジシャン・オブ・ブラック・イリュージョン
- [x] TDIL-JP018	Magician's Robe	マジシャンズ・ローブ
- [x] TDIL-JP019	Magician's Rod	マジシャンズ・ロッド
- [x] TDIL-JP020	Master Peace, the True Dracoslayer	真竜剣士マスターＰ
- [x] TDIL-JP021	Metalphosis Steeleren	メタルフォーゼ・スティエレン
- [x] TDIL-JP022	Metalphosis Silvbird	メタルフォーゼ・シルバード
- [x] TDIL-JP023	Metalphosis Goldriver	メタルフォーゼ・ゴルドライバー
- [x] TDIL-JP024	Metalphosis Volflame	メタルフォーゼ・ヴォルフレイム
- [x] TDIL-JP025	Agnimazd Vanisher, the True Dracoemperor	真竜皇アグニマズドＶ
- [x] TDIL-JP026	Dinomist Ankylos	ダイナミスト・アンキロス (100909104)
- [x] TDIL-JP027	Tramid Dancer	トラミッド・ダンサー (100909109)
- [x] TDIL-JP028	Tramid Hunter	トラミッド・ハンター
- [x] TDIL-JP029	Tramid Master	トラミッド・マスター
- [x] TDIL-JP030	Tramid Sphinx	トラミッド・スフィンクス
- [x] TDIL-JP031	Shiranui Sage	不知火の隠者 (100909103)
- [x] TDIL-JP032	Toon Dark Magician	トゥーン・ブラック・マジシャン (100909107)
- [x] TDIL-JP033	Scapeghost	スケープ・ゴースト
- [x] TDIL-JP034	Block Dragon	ブロックドラゴン
- [x] TDIL-JP035	Amaterasu	天照大神
- [x] TDIL-JP036	Black Dragon Ninja	黒竜の忍者
- [x] TDIL-JP037	Spell Strider‎‎	マジック・ストライダー
- [x] TDIL-JP038	Electrifying Mustangun	放電ムスタンガン
- [x] TDIL-JP039	Totem Five	トーテム・ファイブ
- [x] TDIL-JP040	Tuning Gum	チューニングガム
- [x] TDIL-JP041	Wrecker Panda	レッカーパンダ
- [x] TDIL-JP042	Fairy Tail - Shirayuki	妖精伝姫－シラユキ
- [x] TDIL-JP043	Metalphosis Adamante	メタルフォーゼ・アダマンテ
- [x] TDIL-JP044	Metalphosis Orihulk	メタルフォーゼ・オリハルク
- [x] TDIL-JP045	Metalphosis Cardinal	メタルフォーゼ・カーディナル
- [x] TDIL-JP046	Nirvana High Paladin	涅槃の超魔導剣士
- [x] TDIL-JP047	Assault Blackwing - Sayo the Hidden Rain	Ａ ＢＦ－雨隠れのサヨ
- [x] TDIL-JP048	Assault Blackwing - Sohaya the Early Summer Rain	Ａ ＢＦ－五月雨のソハヤ
- [x] TDIL-JP049	Assault Blackwing - Onimaru the Divine Swell	Ａ ＢＦ－神立のオニマル
- [x] TDIL-JP050	Red Dragon Archfiend Tyrant	レッド・デーモンズ・ドラゴン・タイラント
- [x] TDIL-JP051	Coral Dragon	瑚之龍
- [x] TDIL-JP052	Ebon Void Magician	虚空の黒魔導師
- [x] TDIL-JP053	Super Hippo Carnival	超カバーカーニバル
- [x] TDIL-JP054	Lunalight Perfume	月光香 (100909105)
- [x] TDIL-JP055	Frightfur Sanctuary	デストーイ・サンクチュアリ
- [x] TDIL-JP056	Forbidden Dark Contract with the Swamp King	魔神王の禁断契約書
- [x] TDIL-JP057	Dark Magic Circle	黒の魔導陣
- [x] TDIL-JP058	Illusion Magic	イリュージョン・マジック
- [x] TDIL-JP059	Magic Expand	黒魔導強化 (100909108)
- [x] TDIL-JP060	Metamor Formation	メタモルＦ
- [x] TDIL-JP061	Metalphosis Fusion	錬装融合
- [x] TDIL-JP062	Tramid Fortress	トラミッド・フォートレス (100909110)
- [x] TDIL-JP063	Tramid Cruiser	トラミッド・クルーザー
- [x] TDIL-JP064	Tramid King Golem	トラミッド・キングゴレム
- [x] TDIL-JP065	Cosmic Cyclone	コズミック・サイクロン
- [x] TDIL-JP066	Pot of Cupidity	強欲で貪欲な壺
- [x] TDIL-JP067	Semi Spell Zone	半魔導帯域
- [x] TDIL-JP068	Card of Soul	 魂のカード
- [x] TDIL-JP069	Fusion Doom Waltz	融合死円舞曲
- [x] TDIL-JP070	King Scarlet	キング・スカーレット
- [x] TDIL-JP071	Magician's Navigate	マジシャンズ・ナビゲート
- [x] TDIL-JP072	Metalphosis Counter	メタルフォーゼ・カウンター
- [x] TDIL-JP073	Metalphosis Combination	メタルフォーゼ・コンビネーション
- [x] TDIL-JP074	Tramid Pulse	古代遺跡の目覚め (100909111)
- [x] TDIL-JP075	Destruction Sword Reminiscence	破壊剣の追憶 (100909106)
- [x] TDIL-JP076	Endless Trap Hole	底なし落とし穴
- [x] TDIL-JP077	Premature Return	早すぎた帰還
- [x] TDIL-JP078	Joining Forces	共闘
- [x] TDIL-JP079	Pendulum Hole	ペンデュラム・ホール
- [x] TDIL-JP080	Examination	検問

**Comment by mercury233** [comment]
There are 32 cards left in TDIL. The news may come out tomorrow. Let us make this plan to avoid duplicated work.

Anyone who decide to write a card, click on the checkbox before the card, to let others know you are working on it.

**Comment by EerieCode** [comment]
If the remaining cards come out in the next few days, I'll probably be too busy with work to do the more complex cards, but I should be able to do some of the simpler ones. Specifically, I'm confident I can do the new Performapals (002-006), "D/D Savant Nicola" (011) and "Red Gardna" (015): I'd tentatively say 047 too, but I can't be 100% sure at the moment.

**Comment by mercury233** [comment]
I'm working on TDIL-JP072 Metalphosis Counter メタルフォーゼ・カウンター, 
and EerieCode is on TDIL-JP011 D/D Savant Nikola ＤＤ魔導賢者ニコラ, 

Who checked those cards?
TDIL-JP015 Red Gardna レッド・ガードナー
TDIL-JP036 Black Dragon Ninja 黒竜の忍者
TDIL-JP038 Electrifying Mustangun 放電ムスタンガン
TDIL-JP039 Totem Five トーテム・ファイブ
TDIL-JP042 Fairy Tail - Shirayuki 妖精伝姫－シラユキ

**Comment by Zayelion** [comment]
Uploading the cards to Salvation but I believe we have to do a recompilation of the `ygopro-core` before things will work correctly. We will keep you guys posted.

**Comment by EerieCode** [comment]
I've checked "Red Gardna" too, but I know nothing about the others.

**Comment by nekrozar** [comment]
I edited that list.
But, I didn't check those cards.
I make those cards except Red Gardna.

**Comment by mercury233** [comment]
@nekrozar do mean you **will** make the 4 cards?

**Comment by nekrozar** [comment]
@mercury233 Exactly.
Will you create those cards, too?

**Comment by mercury233** [comment]
@nekrozar let me do
TDIL-JP039 Totem Five トーテム・ファイブ
TDIL-JP042 Fairy Tail - Shirayuki 妖精伝姫－シラユキ

**Comment by destdev** [comment]
I checked
TDIL-JP036 Black Dragon Ninja 黒竜の忍者
TDIL-JP038 Electrifying Mustangun 放電ムスタンガン
TDIL-JP039 Totem Five トーテム・ファイブ
TDIL-JP042 Fairy Tail - Shirayuki 妖精伝姫－シラユキ

sorry, black dragon ninja took me much longer than expected
I'll upload it soon

**Comment by mercury233** [comment]
@destdev so you didn't do 038, 039, 042 yet? I'm on 039 now.

**Comment by destdev** [comment]
nope, I'm done with Black dragon ninja now, haven't started the others yet

**Comment by Zayelion** [comment]
Thank you guys for all your hard work!

**Comment by nekrozar** [comment]
I make Shirayuki.

**Comment by destdev** [comment]
ok, I'll make 038 then

**Comment by EerieCode** [comment]
I have only "Red Gardna" left, I'll upload it within a few hours.

2016-04-07 15:27 GMT+02:00 dest <notifications@github.com>:

**Comment by mercury233** [comment]
@EerieCode Let me do Red Gardna if you are busy now.

**Comment by EerieCode** [comment]
It would be helpful, thank you! I'm afraid I won't be free for a few
hours...

2016-04-07 17:12 GMT+02:00 Mercury233 <notifications@github.com>:

**Comment by mercury233** [comment]
OK, it is all done. Good job!
