### ISSUE TITLE
Soul Fusion(SOFU) - Remaining cards

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro-pre-script#196]
- [x] 009: ダイナレスラー・パンクラトプス
- [x] 012: 墓守の神職
- [x] 013: 墓守の霊術師
- [x] 014: オルフェゴール・カノーネ
- [x] 015: オルフェゴール・スケルツォン
- [x] 016: オルフェゴール・ディヴェル
- [x] 017: 星遺物-『星杖』
- [x] 023: 魔神儀-ペンシルベル
- [x] 024: 魔神儀-ブックストーン
- [x] 026: 幻妖フルドラ
- [x] 027: 光の精霊 ディアーナ
- [x] 029: クマモール
- [x] 031: トークンコレクター
- [x] 032: 通販売員
- [x] 038: ダイプレクサ・キマイラ
- [x] 043: オルフェゴール・ガラテア
- [x] 044: オルフェゴール・ロンギルス
- [x] 045: オルフェゴール・オーケストリオン
- [x] 046: ヴェルスパーダ・パラディオン
- [x] 048: 竜絶蘭
- [x] 055: ネクロバレーの玉座
- [x] 057: オルフェゴール・バベル
- [x] 058: オルフェゴール・プライム
- [x] 059: オルフェゴール・アインザッツ
- [x] 063: 深淵の宣告者
- [x] 064: コンセントレイト
- [x] 065: おろかな重葬
- [x] 066: パラレル・パンツァー
- [x] 068: ネクロバレーの神殿
- [x] 069: 永遠なる銀河
- [x] 070: オルフェゴール・アタック
- [x] 071: オルフェゴール・コア
- [x] 074: クローラー・パラディオン
- [x] 075: 死魂融合
- [x] 076: インヴィンシブル・ヘイロー
- [x] 077: 通行増税
- [x] 079: 一色即発
- [x] 080: 素早きは三文の徳

**Comment by nekrozar** [comment]
Maybe we should update ocgcore by オルフェゴール・バベル.

**Comment by mercury233** [comment]
what about
```lua
e:SetType(EFFECT_TYPE_QUICK_O)
function c101006045.condition(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetCurrentChain()==0 or Duel.IsPlayerAffectedByEffect(101006057)
end
```
(we need FAQ to confirm the speed of those effect in the own player's turn)

**Comment by destdev** [comment]
that seems fine, yes
from reading the current translation I'd say they should be considered regular Ignition effects during your own turn, thus without any confirmation I think it should look like this:
```lua
e:SetType(EFFECT_TYPE_QUICK_O)
function c101006045.condition(e,tp,eg,ep,ev,re,r,rp)
	return (Duel.GetTurnPlayer()==tp and (Duel.GetCurrentPhase()==PHASE_MAIN1 or Duel.GetCurrentPhase()==PHASE_MAIN2) and Duel.GetCurrentChain()==0) or Duel.IsPlayerAffectedByEffect(101006057)
end
```

**Comment by EerieCode** [comment]
Agreed. It seems pretty similar in concept to the effects of the Super Quant Xyz monsters, so the same method should work in theory.

**Comment by destdev** [comment]
I totally forgot about the Super Quants...
Yea, that would be way easier, just need to check for the flag then in those 2 conditions. However there seems to be a slight difference in the wording?
I still can't read that text properly, and the translations I found speak of the wording as "during either player's turn" (like the Quants) or also "during your opponent’s turn". I based the condition out of the second option. Uh, if anyone could clearify what translation would be more accurate?

**Comment by EerieCode** [comment]
I usually find the translation on the Yugipedia to be more accurate, they're listing the "either player" option at the moment. I'd need to check the OCG text to be 100% sure, but I'm on phone right now...

**Comment by EerieCode** [comment]
Alright, I've asked other players more fluent in Japanese. Apparently, what the Organization used is a literal translation of the text, something along the lines of "the effect can be activated during the opponent's turn": however, that is also the wording used for Quick effects in the OCG, meaning the Yugipedia translation would be more precise. That being said, they weren't 100% sure either, so I think we'll need tomorrow's rulings for confirmation.

**Comment by nekrozar** [comment]
> https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=22035
> 自分のフィールドゾーンに「オルフェゴール・バベル」が表側表示で存在し、『①：このカードがフィールドゾーンに存在する限り、元々のカード名に「オルフェゴール」を含む、自分フィールドのリンクモンスター及び自分の墓地のモンスターが発動する効果は、相手ターンでも発動できる効果になる』効果が適用されています。
> 
> この状況で、モンスターゾーンや墓地の「オルフェゴール」と名のついたモンスターの効果を発動する場合、**誘発即時効果として発動される事になります**が、ダメージステップに発動できるようになりますか？
