### ISSUE TITLE
Owner Change Over

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro-pre-script#2]
@Fluorohydride we are going to turn this repo over to you. Can you give access rights to the people contributing to the project, and let us know when you are ready to accept it?

They are :
@ChibiChanNya 
@StormWulf 
@destdev 
@HelixReactor 
@ygohack137
@EerieCode
@DailyShana

If Im forgetting anyone people sound off.

**Comment by StormWulf** [comment]
@OneShot119
@Ragna_Edge

**Comment by Zayelion** [comment]
Ok I've pasted ownership over to @Fluorohydride, waiting on him to accept
