### ISSUE TITLE
Tramid Dancer

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#20]
![alt text](https://puu.sh/o9xjT/eb3b3d0fc3.jpg "Tramid Dancer red text")
https://github.com/Fluorohydride/ygopro-pre-script/blob/248ccb9a89ad24ebcc3aff035fff3fc4371572f1/scripts/TDIL-JP/c100909109.lua#L46

When the user attempts to activate Tramid Dancer's first effect `Once per turn: You can target 1 "Tramid" card in your Graveyard; shuffle it into the Deck, and if you do, all Rock-Type monsters you currently control gain 500 ATK and DEF`, the red text above appears and nothing else happens.

**Comment by EerieCode** [comment]
The error is actually at the line 40. You're searching the target using
.filter when it should be .tdfilter: the program can't find the function,
so it can't select a target, thus tc is nothing when it shouldn't be.

2016-04-07 17:06 GMT+02:00 Jeff Falberg <notifications@github.com>:
