### ISSUE TITLE
Issue Neos Fusion

### ISSUE THREAD

**Issue by nekrozar** [Fluorohydride/ygopro-pre-script#204]
https://yu-gi-oh.jp/index.php?page=details&&id=394

> ①：自分の手札・デッキ・フィールドから融合モンスターカードによって決められた融合素材モンスターを墓地へ送り、「Ｅ・ＨＥＲＯ ネオス」を含むモンスター２体のみを素材とするその融合モンスター１体を召喚条件を無視してＥＸデッキから特殊召喚する。
> このカードの発動後、ターン終了時まで自分はモンスターを特殊召喚できない。
> ②：「Ｅ・ＨＥＲＯ ネオス」を融合素材とする自分フィールドの融合モンスターが戦闘・効果で破壊される場合、または自身の効果でＥＸデッキに戻る場合、代わりに墓地のこのカードを除外できる。

However, current version can't get fusion material count.
Do you have any good ideas?

**Comment by mercury233** [comment]
Same way as _Miracle Synchro Fusion_? We need to update all Neos fusion monsters to implement the second effect of this card anyways.

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/b7a0599080eb4db0f8678aa23974c573c0edc34f
https://github.com/Fluorohydride/ygopro-pre-script/commit/6b090edaf448f284f3e1c09c563d50305f70c10c

How about this way?

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/pull/209
I think _Neos Fusion_ use EFFECT_SEND_REPLACE.
