### ISSUE TITLE
Forbidden Dark Contract with the Swamp King

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#21]
![alt text](https://puu.sh/oa4RU/3820baa051.jpg "Forbidden Dark Contract with the Swap King error")

If the monster Special Summoned from the hand by Forbidden Dark Contract goes to the Extra Deck, it lets the player fuse with it from the Extra Deck. This should be fixed.

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/blob/master/scripts/TDIL-JP/c100909056.lua#L80

**Comment by nekrozar** [comment]
Sorry, I mistook.
https://github.com/Fluorohydride/ygopro-pre-script/commit/2dc0bb4fa6da20f6ba25595ae2be8f38673bd665 fixed.
