### ISSUE TITLE
ygopro-script update for counters

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#22]
Zushin the Sleeping Giant needs an update to match the counter updates from https://github.com/StormWulf/ygopro-scripts/commit/fefe8ad1691ae4459f632d3f8b5e37dfb640313a

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/d861844849c49e5670fa626bb3b70b2d08015f10 updated. Thank you!
