### ISSUE TITLE
DANE - Remaining cards

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro-pre-script#234]
- [x] 006: ダイナレスラー・エスクリマメンチ
- [x] 008: ダイナレスラー・マーシャルアンガ
- [x] 011: バスター・スナイパー
- [x] 022: 擾乱騒蛇ラウドクラウド
- [x] 023: エクシーズ・スライドルフィン
- [x] 025: 儚無みずき
- [x] 026: ハンディ・ギャロップ
- [x] 028: ロー・キューピット
- [x] 049: 落消しのバズロミノ
- [x] 053: タイラント・ダイナ・フュージョン
- [x] 060: 転臨の守護竜
- [x] 061: テスタメント・パラディオン
- [x] 063: 亡龍の旋律
- [x] 064: 魔鐘洞
- [x] 065: モルトシュラーク
- [x] 066: スタンド・イン
- [x] 067: 強制切断
- [x] 074: オルフェゴール・クリマクス
- [x] 075: 星遺物の齎す崩界
- [x] 076: 星遺物の対焉

**Comment by purerosefallen** [comment]
Working on progress by YGOPro 222DIY Community:
101008067 移花接木

**Comment by TanakaKotoka** [comment]
W 101008028

**Comment by purerosefallen** [comment]
All set. Waiting for submission.

**Comment by mercury233** [comment]
Thank you all!
