### ISSUE TITLE
VJump - January 2019

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro-pre-script#249]
- [x] 100200158 : HSRカイドレイク

- [x] 100236100 : 青眼の究極亜竜
- [x] 100236101 : マジシャン・オブ・ブラックカオス・MAX
- [x] 100236102 : 守護神エクゾディア
- [x] 100236103 : 守護神官マナ
- [x] 100236104 : 真紅眼の亜黒竜
- [x] 100236105 : ネオ・カイザー・グライダー
- [x] 100236106 : Sin Cross
- [x] 100236118 : 方界縁起

- [x] 100308001 : 創聖魔導王 エンディミオン
- [x] 100308040 : 魔導耀士 デイブレイカー

- [x] 100412007 : 無限起動リヴァーストーム
- [x] 100412016 : ウィッチクラフト・シュミッタ
- [x] 100412028 : 呪眼の死徒 メドゥサ
- [x] 100412030 : 呪眼の眷属 バジリウス
- [x] 100412033 : 呪眼領閾－パレイドリア－
- [x] 100412034 : 喚忌の呪眼
- [x] 100412035 : 惨禍の呪眼
- [x] 100412036 : 静冠の呪眼
- [x] 100412037 : 妬絶の呪眼
- [x] 100412038 : 死配の呪眼
- [x] 100412039 : 断罪の呪眼
- [x] 100412100 : 無限起動ゴライアス

**Comment by TanakaKotoha** [comment]
W 100236106

**Comment by purerosefallen** [comment]
(W=In progress, P=Pull request sent)


P 100236104 FW空鸽
W 100236106  Tanaka Kotoha
W 100308040 FW空鸽
