### ISSUE TITLE
Galaxy-Eyes Cipher Dragon

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#26]
The stolen monster doesn't obtain the 3000 ATK, and it doesn't return to the opponent's field at the end of the turn.

![no ATK change](https://i.imgur.com/5xhucMJ.jpg)
![no expiration](https://i.imgur.com/OQKby3I.png)

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/76c2f8c6ef0567ddca81d11ee5fca8f71579b3e0 Fixed. Thank you!
