### ISSUE TITLE
Silent Swordman

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#27]
Silent Swordsman is able to summon Silent Sword as a monster with its effect, but it should only summon monsters

![Silent Swordsman bug](https://i.imgur.com/spGzzob.png)

**Comment by mercury233** [comment]
Thanks, I forget to limit it to monster. But Silent Sword(沈黙の剣) shouldn't be "Silent Swordsman(サイレント・ソードマン)" card.
