### ISSUE TITLE
Spiritual Swords of Revealing Light (MVP1: 78625592)

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#29]
Shouldn't the reset condition for the flag be PHASE_DAMAGE_CAL instead of PHASE_END? The effect can be used once per battle, not once per Battle Phase: it should be usable multiple times per turn, like "Crystal Wing Synchro Dragon".

**Comment by mercury233** [comment]
Thanks, fixed.
