### ISSUE TITLE
Card names

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#3]
I'm glad that other scripters are collaborating in this repo, but can we please include English names in addition to the Japanese? I'm aware that any English name is unofficial, but it would be more convenient for the English scripters.

**Comment by mercury233** [comment]
Sorry I forgot to add English names.

**Comment by Zayelion** [comment]
https://github.com/Ygoproco/Live/pull/95/files comparison needed.

**Comment by StormWulf** [comment]
Thank you very much, Mercury.
