### ISSUE TITLE
Dimension Sphinx (MVP1: 17787975)

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#30]
Its damage effect states "Once per Battle Step", similar to "Number 9: Dyson Sphere", but with the current script it can be used only once per turn.

**Comment by EerieCode** [comment]
Also, I think "Dimension Mirage" (80560728) has a similar issue: its effect that forces the monster to attack again should be usable more than once per turn.

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-scripts/commit/92679e230e37c4704d9d507d40d570589c6ee678
