### ISSUE TITLE
The Kaiju Files red text

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#31]
Red text occurs when playing the card

![Kaiju Files red text](https://images-1.discordapp.net/eyJ1cmwiOiJodHRwOi8vcHV1LnNoL292eDdXLzZiNjFmNWFmOTMuanBnIn0.niQ6pGVbrU5kmvumCzoOZ2bqz2I.jpg)

**Comment by destdev** [comment]
I don't get that error when playing the card or use that effect.
What exactly did you do to get this.
