### ISSUE TITLE
Chem Beast issues

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#38]
- [x] `Chemical Beast Oxine Ox [100910025]` : When the player selects a card from the hand to Special Summon, the game freezes
- [x] `Chemical Beast Hydron Hawk [100910023]` : When the player selects a monster to revive, the animation of the target appears as if summoned, but doesn't make it to the field
- [ ] `Spark Field [100910059]` : Red text
- [x] `Advanced Chemical Beast Hy Dragon [100910100]` : When the player use this card to protect a Gemini by picking another Gemini, it will activate again. If the player picks a non-Gemini afterward, no cards are destroyed. ![Hy Dragon Sub issue](https://images-2.discordapp.net/.eJwNyMENwyAMAMBdGAADLg1kG0QQiZrYCDvqo-ru7T3vY-55mtXsqkNWgO2QynOzojxLb7Yz97OVcYitfEFRLXW_GqmAT7i46DI6dCH54J_gMz5CDMv_EuYUM8JNL-I32UHdfH8FiyLZ.WHZY5w67Q-5V-xsWh686DNKdCIQ.png)

**Comment by mercury233** [comment]
Is those issues fixed now?

**Comment by StormWulf** [comment]
These were mostly core issues

However, Carbon Crab isn't working when the player tries to use its effect

**Comment by mercury233** [comment]
I'll fix it tomorrow. And add SPDS cards.

**Comment by destdev** [comment]
carbon crab works perfectly fine for me in the current state

**Comment by StormWulf** [comment]
The issue is that it's completely arbitrary when Crab decides to work or not. Sometimes, it fails, but other times it works fine.

**Comment by StormWulf** [comment]
There however is an issue with Hy Dragon, as I noted above

**Comment by destdev** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/cacf13a221fe8486b969f8706b2db97c93c0d17c
this should fix that
for Crab, make sure to have at least 2 gemini in the deck (1 that is able to grave and 1 that can be added to the hand) ... other than that I can't see anything that could prevent that effect from working ...

**Comment by StormWulf** [comment]
There's this red text that also occasionally occurs with Spark Field

![Spark Field red text](http://image.prntscr.com/image/7c6ea033586642a48b0945f69780d31b.png)

**Comment by destdev** [comment]
can't really find anything that could cause that to become nil...
what means "occasionally"? Random times or is there a pattern perhaps?
I'll test around a bit more, maybe we'll find something...
