### ISSUE TITLE
Missing scripts

### ISSUE THREAD

**Issue by Lyris12** [Fluorohydride/ygopro-pre-script#386]
Scripts for the following cards are currently missing:
- [ ] `100200176` Machina Metalcrunch
- [ ] `100200177` Speedroid Block-n-Roll
- [ ] `100200178` Speedroid CarTurbo
- [ ] `100200179` D/D Dog
- [ ] `100310041` Malefactors' Command
- [ ] `101101001` Magic Knight Gaia
- [ ] `101101002` Cursed Dragon - Curse of Dragon
- [ ] `101101003` Howitzer Catapult Turtle
- [ ] `101101004` Soldier Gaia the Fierce Knight
- [ ] `101101029` Nemesys Keystone
- [ ] `101101036` Megalith Phul
- [ ] `101101037` Gaia the Magical Dragon Champion
- [ ] `101101048` Ancient Warriors Allied Generals - Shuanglong
- [ ] `101101049` Rushing Gaia
- [ ] `101101050` Spiral Fusion
- [ ] `101101059` Magallanica, the Deep Sea City
- [ ] `101101068` Spiral Discharge
- [ ] `101101069` Spiral Reborn
- [ ] `101101076` Shaddoll Ruq
- [ ] `100338001` Raviel, Lord of Phantasms - Shimmering Scraper
- [ ] `100338003` Dark Beckoning Beast
- [x] `100338005` Dimension Fusion Destruction (#372)
- [x] `100338019` Cerulean Sky Fire (#397)
- [x] `100338034` Hyper Blaze (#397)

I _would_ script these myself, but I am not sure how far y'all are in terms of progress on scripting these cards...

**Comment by mallu11** [comment]
I will write all missing scripts this weekend.If you had written some missing scripts or you want to write the scripts for this repository,you can open a new pull request.

**Comment by Lyris12** [comment]
Thanks, and alright; thanks!

**Comment by XGlitchy30** [comment]
I can script Cerulean Sky Fire and Hyper Blaze
