### ISSUE TITLE
Destiny HERO issues

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#39]
- [x] `Destiny HERO - Decisionguy [100405002]` : At the start of the duel, this red text occurs ![Decisionguy red text](http://image.prntscr.com/image/713a92bfd2314878be65a4137e9482aa.png)
- [ ] `Destiny HERO - Dynamiteguy [100405003]` : According to its text, it should only reduce the damage that the owner of the card would take, not both players

**Comment by destdev** [comment]
that text is not from decisionguy, that's also from Dynamiteguy and most propably the cause of your other failure
fixed
https://github.com/Fluorohydride/ygopro-pre-script/commit/c8ecff257358beceb53ae2e3237291febbf041b2
