### ISSUE TITLE
Permission for use

### ISSUE THREAD

**Issue by Zayelion** [Fluorohydride/ygopro-pre-script#4]
@EerieCode is it ok with we use your script that you have been pushing to @YGOProCo ? and @YGOProCo is it ok if we use the scripts you have in production. The intent is if they are the best scripts as decided by the community then to push them into ygopro-scripts.

If we dont get a response we are going to assume it is ok.

**Comment by EerieCode** [comment]
As far as I'm concerned, there's really no problem. Be careful, though: new bug reports come out almost every day, so I can't guarantee the scripts I made are 100% correct; you might want to double-check them before using them.

**Comment by mercury233** [comment]
Thank you @EerieCode !
