### ISSUE TITLE
INOV scripting progress

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro-pre-script#41]
- [x] INOV-JP001	Dragon Core Accursed	竜核の呪霊者
- [x] INOV-JP002	Performapal Whim Witch	ＥＭウィム・ウィッチ
- [x] INOV-JP003	Performapal Allcover Hippo	EMオールカバー・ヒッポ
- [x] INOV-JP004	Performapal Seal Eel	EMシール・イール
- [x] INOV-JP005	Performapal Chain Giraffe	EMチェーンジラフ
- [x] INOV-JP006	Predator Plant Fly Hell	捕食植物フライ・へル
- [x] INOV-JP007	Predator Plant Moray Nepenthes	捕食植物モーレイ・ネペンテス
- [x] INOV-JP008	Predator Plant Squid Drosera	捕食植物スキッド・ドロセーラ
- [x] INOV-JP009	Superheavy Samurai Soul Arbitrator	超重武者装瑠チュウサイ
- [x] INOV-JP010	Cipher Twin Raptor	光波双顎機
- [x] INOV-JP011	Cipher Mirror Knight	光波鏡騎士
- [x] INOV-JP012	Cardian - Hagi ni Inoshishi	花札衛－萩に猪－
- [x] INOV-JP013	Cardian - Momiji ni Shika	花札衛－紅葉に鹿－
- [x] INOV-JP014	Cardian - Botan ni Cho	花札衛－牡丹に蝶－
- [x] INOV-JP015	Crystron Quon	水晶機巧－クオン
- [x] INOV-JP016	Crystron Citri	水晶機巧－シトリィ
- [x] INOV-JP017	Crystron Prasirator	水晶機巧－プラシレータ
- [x] INOV-JP018	Crystron Smoger	水晶機巧－スモーガー
- [x] INOV-JP019	Crystron Thystvern	水晶機巧－シストバーン
- [x] INOV-JP020	Crystron Rosenix	水晶機巧－ローズニクス
- [x] INOV-JP021	Bahrstos Fuhrer, the True Dracoruler	真竜皇バハルストスF
- [x] INOV-JP022	Raremetalfoes Bismagia	レアメタルフォーゼ・ビスマギア
- [x] INOV-JP023	Chemical Beast Hydron Hawk	化合獣ハイドロン・ホーク
- [x] INOV-JP024	Chemical Beast Carbon Crab	化合獣カーボン・クラブ
- [x] INOV-JP025	Chemical Beast Oxine Ox	化合獣オキシン・オックス
- [x] INOV-JP026	Advanced Chemical Beast Dyoxen	進化合獣ダイオーキシン
- [x] INOV-JP027	Advanced Chemical Beast Hy Dragon	進化合獣ヒュードラゴン (100910100)
- [x] INOV-JP028	Red-Eyes Meteor Dragon	真紅眼の凶星竜－メテオ・ドラゴン
- [x] INOV-JP029	PSY-Frame Multi-Threader	ＰＳＹフレーム・マルチスレッダー
- [x] INOV-JP030	Graydle Slime Jr.	グレイドル・スライム﻿Ｊｒ．
- [x] INOV-JP031	Aromaseraphy Angelica	アロマセラフィ－アンゼリカ
- [x] INOV-JP032	Dokidoki‎‎	怒気土器
- [x] INOV-JP033	Torque Tune Gear	トルクチューン・ギア
- [x] INOV-JP034	Pandora's Treasure Box	パンドラの宝具箱
- [x] INOV-JP035	Fairy Tail - Talia	妖精伝姫－ターリア
- [x] INOV-JP036	Cyber Angel - Vishnu	サイバー・エンジェル－美朱濡－
- [x] INOV-JP037	Sauravis, the Crowned Ancient Sage	古聖戴サウラヴィス
- [x] INOV-JP038	Starve Venom Fusion Dragon	スターヴ・ヴェノム・フュージョン・ドラゴン
- [x] INOV-JP039	Fullmetalfoes Alkahest	フルメタルフォーゼ・アルカエスト
- [x] INOV-JP040	Metalfoes Mythriel	メタルフォーゼ・ミスリエル
- [x] INOV-JP041	Ryuuseiryuu Meteo Black Dragon	流星竜メテオ・ブラック・ドラゴン
- [x] INOV-JP042	Superheavy Samurai Ninja Sarutobi	超重忍者サルト－Ｂ
- [x] INOV-JP043	Cardian - Inoshikacho	花札衛－猪鹿蝶－
- [x] INOV-JP044	Crystron Quondam	水晶機巧－クオンダム
- [x] INOV-JP045	Crystron Ametrix	水晶機巧－アメトリクス
- [x] INOV-JP046	Crystron Phoenixion	水晶機巧－フェニキシオン
- [x] INOV-JP047	Aromaseraphy Rosemary	アロマセラフィ－ローズマリー
- [x] INOV-JP048	Denglong, Origin of the Yang Zing	源竜星－ボウテンコウ
- [x] INOV-JP049	Dark Requiem Xyz Dragon	ダーク・レクイエム・エクシーズ・ドラゴン
- [x] INOV-JP050	Super Chemical Beast Methane Hyd	超化合獣メタン・ハイド
- [x] INOV-JP051	Tellarknight Vatraemus	煉獄の騎士 ヴァトライムス
- [x] INOV-JP052	Treatoad	餅カエル
- [x] INOV-JP053	Amazing Pendulum	アメイジング・ペンデュラム
- [x] INOV-JP054	Rank-Up-Magic The Phantom Knights of Launch	ＲＵＭ－幻影騎士団ラウンチ
- [x] INOV-JP055	Hanazumi	花積み
- [x] INOV-JP056	Chokoikoi	超こいこい
- [x] INOV-JP057	Krystal Potential	クリスタルＰ
- [x] INOV-JP058	Fullmetalfoes Fusion	重錬装融合
- [x] INOV-JP059	Spark Field	化合電界
- [x] INOV-JP060	Red-Eyes Insight	レッドアイズ・インサイト
- [x] INOV-JP061	Igknight Unite	イグナイト・ユナイト
- [x] INOV-JP062	Genesis Tellarknight	創星の因子
- [x] INOV-JP063	"A" Cell Recombination Device	「Ａ」細胞組み換え装置
- [x] INOV-JP064	Fairy's Blessing	精霊の祝福
- [x] INOV-JP065	Pot of Avidity	大欲な壺
- [x] INOV-JP066	Quarantine	検疫
- [x] INOV-JP067	King's Synchro	王者の調和
- [x] INOV-JP068	Double Cipher	二重光波
- [x] INOV-JP069	Cipher Bit	光波防輪
- [x] INOV-JP070	No Cheaters Allowed	イカサマ御法度
- [x] INOV-JP071	Crystron Entry	クリストロン・エントリー
- [x] INOV-JP072	Crystron Impact‎‎	クリストロン・インパクト
- [x] INOV-JP073	Burn Out	完全燃焼
- [x] INOV-JP074	PSY-Frame Accelerator	ＰＳＹフレーム・アクセラレーター
- [x] INOV-JP075	Graydle Combat	グレイドル・コンバット
- [x] INOV-JP076	Qliphort Down	機殻の凍結
- [x] INOV-JP077	Nine Branches of the Yang Zing	竜星の九支 (100910101)
- [x] INOV-JP078	Dimension Barrier‎	次元障壁
- [x] INOV-JP079	Summon Gate	サモン・ゲート
- [x] INOV-JP080	Present Card	プレゼントカード

**Comment by mercury233** [comment]
There are 22 cards left in INOV. The news may come out tomorrow. Let us make this plan to avoid duplicated work.

Anyone who decide to write a card, click on the checkbox before the card, to let others know you are working on it. Github will automatically record it.

**Comment by EerieCode** [comment]
I should be able to do the new Performapals between 003 and 005. Aside from that, I really can't say at the moment, I have to see the effects first.

**Comment by mercury233** [comment]
@EerieCode If you are busy now, let me do INOV-JP005 Performapal Chain Giraffe.

**Comment by EerieCode** [comment]
That would be nice, thank you! Sorry, work took longer than expected...

**Comment by mercury233** [comment]
OK, it is all done, good job!
