### ISSUE TITLE
Snowflower Snowdrop Second Effect not working(Dueling Nexus)

### ISSUE THREAD

**Issue by vizele** [Fluorohydride/ygopro-pre-script#416]
Snowflower Snowdrop's second effect, which changes the level of all plant monsters on the field, does not come up when clicking on the card after summoning it

**Comment by mercury233** [comment]
any screenshot?

**Comment by vizele** [comment]
this is right after special summoning snowflower snowdrop after using her effect
![Screen Shot 2020-03-11 at 3 46 43 PM](https://user-images.githubusercontent.com/62006215/76471356-a791d380-63af-11ea-9a8d-2b4c3fa75beb.png)

**Comment by vizele** [comment]
there is no activation flash bordering her

**Comment by mercury233** [comment]
the original ygopro don't have this problem, you should report to Dueling Nexus

**Comment by vizele** [comment]
original ygo pro doesnt even have the snowflower cards
