### ISSUE TITLE
BUG: Abyss Script - Rise of the Dark Ruler not triggering when destroyed Set

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#43]
When Abyss Script - Rise of the Dark Ruler is destroyed while Set, it's not triggering its second effect to add cards to the hand. When testing it, there was an Abyss Actor in the Extra Deck, and there were enough targets in the Deck.

**Comment by destdev** [comment]
seems to work perfectly fine for me
make sure to have the latest fix applied
