### ISSUE TITLE
Darklord of Pleasure script issue

### ISSUE THREAD

**Issue by sleeser** [Fluorohydride/ygopro-pre-script#432]
Darklord of Pleasure beta code:101101024 script is not right according to reports im getting. tested on 2 platforms.
"If this card is Normal or Special Summoned: You can activate this effect; you cannot activate monster effects for the rest of this turn, except Fairy monsters', also take 2 "Darklord" monsters with different Levels from your hand and/or Deck, except "Darklord of Pleasure", Special Summon 1 of them to your opponent's field in Defense Position, and if you do, add the other to your hand. You can only use this effect of "Darklord of Pleasure" once per turn."

want to bring your attention to
"also take 2 "Darklord" monsters with different Levels from your hand **and/or** Deck"
right now 1 monster is firstly picked from the hand and the 2nd is from the deck, but thats not how the card suppose to work.
you should be able to pick 2 monsters from the deck/hand and then pick which one to summon to enemy field.

**Comment by mallu11** [comment]
It will be fixed in https://github.com/Fluorohydride/ygopro-pre-script/pull/431.
