### ISSUE TITLE
New card bugs

### ISSUE THREAD

**Issue by BlackBallista** [Fluorohydride/ygopro-pre-script#45]
Red text on Frightfur Kraken (100406020)

http://i.imgur.com/m2iA95v.jpg

His effect to switch himself to defence positiona fter the BP is not working
The rest of the card is fine

Fluffal octo's effect to return banished monsters to grave cannot be activated (100406014)

red text present
http://imgur.com/a/LpEMV

Clearwing fast dragon (100211001) is able to target your own monsters even though it shouldnt
no red text

**Comment by destdev** [comment]
fixed https://github.com/Fluorohydride/ygopro-pre-script/commit/83e96d823484ad680c186a7421783d602ce7c528
