### ISSUE TITLE
RATE scripting progress

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro-pre-script#50]
- [x] 	RATE-JP001	Descend Dragon Magician	降竜の魔術師
- [x] 	RATE-JP002	Performapal Return Tantan	ＥＭリターンタンタン
- [x] 	RATE-JP003	Performapal Dag Daggerman	EMダグ・ダガーマン 
- [x] 	RATE-JP004	Performapal Laughmaker	EMラフメイカー
- [x] 	RATE-JP005	Speedroid OMK Gum	ＳＲ－ＯＭＫガム
- [x] 	RATE-JP006	Speedroid Bamboo Horse	ＳＲバンブー・ホース
- [x] 	RATE-JP007	Wind Witch - Ice Bell	ＷＷ－アイス・ベル
- [x] 	RATE-JP008	Wind Witch - Snow Bell	ＷＷ－スノウ・ベル
- [x] 	RATE-JP009	Parasite Fusioner	パラサイト・フュージョナー
- [x] 	RATE-JP010	Cyber Tutubon	サイバー・チュチュボン
- [x] 	RATE-JP011	Cipher Étranger	光波異邦臣
- [x] 	RATE-JP012	Flower Cardian Cherry Blossom with Curtain	花札衛－桜に幕－
- [x] 	RATE-JP013	Ancient Gear Hunting Hound	古代の機械猟犬
- [x] 	RATE-JP014	Juunishishi Molmorat	十二獣モルモラット
- [x] 	RATE-JP015	Juunishishi Rabbina	十二獣ラビーナ
- [x] 	RATE-JP016	Juunishishi Viper	十二獣ヴァイパー
- [x] 	RATE-JP017	Juunishishi Thoroughblade	十二獣サラブレード
- [x] 	RATE-JP018	Juunishishi Ram	十二獣ラム
- [x] 	RATE-JP019	True King Lithosazim, the Disaster	真竜皇リトスアジムD
- [x] 	RATE-JP020	Crystron Rion	水晶機巧－リオン
- [x] 	RATE-JP021	Crystron Sulphafnir	水晶機巧－サルファフナー
- [x] 	RATE-JP022	Esprit Bird - Shinobi Garasu	霊魂鳥－忍鴉
- [x] 	RATE-JP023	Esprit Bird - Kannagi Tsuru	霊魂鳥－巫鶴
- [x] 	RATE-JP024	Esprit Bird - Den Hato	霊魂鳥－伝鳩
- [x] 	RATE-JP025	Envoy of Chaos	混沌の使者
- [x] 	RATE-JP026	Spiritual Beast Tamer Winda	精霊獣使い ウィンダ
- [x] 	RATE-JP027	Tierra, Goddess of Rebirth	創星神 ｔｉｅｒｒａ
- [x] 	RATE-JP028	Phantasmal Miscellasaurus	幻創のミセラサウルス
- [x] 	RATE-JP029	Apprentice Piper	見習い魔笛使い
- [x] 	RATE-JP030	Kawanokami	河伯
- [x] 	RATE-JP031	Yokotuner	横綱犬
- [x] 	RATE-JP032	All-Consuming Glutton	百万喰らいのグラットン
- [x] 	RATE-JP033	Wightprincess	ワイトプリンセス
- [x] 	RATE-JP034	Metrognome	メトロンノーム 
- [x] 	RATE-JP035	Fairy Tail - Cinderella	妖精伝姫-シンデレラ
- [x] 	RATE-JP036	Cyber Angel Nasateiya	サイバー・エンジェル－那沙帝弥－
- [x] 	RATE-JP037	Esprit Lord - Himekujaku	霊魂鳥神－姫孔雀
- [x] 	RATE-JP038	Esprit Lord - Hikokujaku	霊魂鳥神－彦孔雀
- [x] 	RATE-JP039	Brave-Eyes Pendulum Dragon	ブレイブアイズ・ペンデュラム・ドラゴン
- [x] 	RATE-JP040	Wind Witch - Crystal Bell	ＷＷ－クリスタル・ベル
- [x] 	RATE-JP041	Ancient Gear Chaos Giant	古代の機械混沌巨人
- [x] 	RATE-JP042	Ancient Gear Devil	古代の機械魔神
- [x] 	RATE-JP043	Wind Witch - Winter Bell	ＷＷ－ウィンター・ベル
- [x] 	RATE-JP044	Superheavy Samurai Ninja Shinobiashi	超重忍者シノビ－Ａ・Ｃ
- [x] 	RATE-JP045	Flower Cardian Five Lights	花札衛－五光－
- [x] 	RATE-JP046	Crystron Glyongandr	水晶機巧-グリオンガンド
- [x] 	RATE-JP047	Homuragami - Shiranui	炎神－不知火
- [x] 	RATE-JP048	Odd-Eyes Raging Dragon	覇王烈竜オッドアイズ・レイジング・ドラゴン
- [x] 	RATE-JP049	Neo Galaxy-Eyes Cipher Dragon	超銀河眼の光波龍
- [x] 	RATE-JP050	Heavy-Armored Train Iron Wolf‎‎	重装甲列車アイアン・ヴォルフ
- [x] 	RATE-JP051	Juunishishi Bullhorn	十二獣ブルホーン
- [x] 	RATE-JP052	Juunishishi Tigress	十二獣タイグリス
- [x] 	RATE-JP053	Juunishishi Drancia	十二獣ドランシア
- [x] 	RATE-JP054	Juunishishi Wildbow	十二獣ワイルドボウ
- [x] 	RATE-JP055	Machine Angel Absolute Ritual	機械天使の絶対儀式
- [x] 	RATE-JP056	Rank-Up-Magic Cipher Ascension	ＲＵＭ－光波昇華
- [x] 	RATE-JP057	Card Regeneration	札再生
- [x] 	RATE-JP058	Zodiac Sign	ゾディアックＳ	(100911100)
- [x] 	RATE-JP059	Juunishishi no Kaikyoku	十二獣の会局	(100911101)
- [x] 	RATE-JP060	Esprit Calling	霊魂の降神
- [x] 	RATE-JP061	Esprit Powerspot	霊魂の拠所
- [x] 	RATE-JP062	Super Soldier Origin	超戦士の萌芽
- [x] 	RATE-JP063	Super Quantal Finisher Alphan Ball	超量必殺アルファンボール
- [x] 	RATE-JP064	Promised Return of the Ritual Beast	霊獣の誓還
- [x] 	RATE-JP065	Foolish Burial with Belongings	おろかな副葬
- [x] 	RATE-JP066	Lawnmowing Next Door	隣の芝刈り
- [x] 	RATE-JP067	Terminal World Next	端末世界NEXT
- [x] 	RATE-JP068	Bewildering Wind	迷い風
- [x] 	RATE-JP069	Cipher Spectrum	光波分光
- [x] 	RATE-JP070	Ancient Gear Reborn	古代の機械蘇生
- [x] 	RATE-JP071	Juunishishi no Hougou	十二獣の方合	(100911102)
- [x] 	RATE-JP072	Esprit Healing	霊魂の円環
- [x] 	RATE-JP073	Universal Beginning	天地開闢
- [x] 	RATE-JP074	Shiranui Style Reincarnation	不知火流 輪廻の陣
- [x] 	RATE-JP075	Majespecter Gust	マジェスペクター・ガスト	(100911103)
- [x] 	RATE-JP076	Void Madness	煉獄の狂宴
- [x] 	RATE-JP077	Purusha Shaddoll Aion	魂源への影劫回帰
- [x] 	RATE-JP078	Shadow Spread Virus	影のデッキ破壊ウイルス
- [x] 	RATE-JP079	Switch Hero	スウィッチヒーロー
- [x] 	RATE-JP080	 Macromorph	肥大化

**Comment by mercury233** [comment]
Let us make this plan to avoid duplicated work.

Anyone who decide to write a card, click on the checkbox before the card, to let others know you are working on it. Github will automatically record it.

**Comment by Zayelion** [comment]
Arent most these coded already?

**Comment by nekrozar** [comment]
Who checked Switch Hero?
Switch Hero's script doesn't exist...

**Comment by destdev** [comment]
Just for info:
I'm sorry, but don't count on me this time, I'm sick and my brain doesn't really work too well atm.

**Comment by mercury233** [comment]
@nekrozar I'm working on it.

**Comment by mercury233** [comment]
Well, I thought I can do _RATE-JP046 Crystron Glyongandr 水晶機巧-グリオンガンド_ but I found it is too hard for me.

**Comment by nekrozar** [comment]
@mercury233 
https://github.com/Fluorohydride/ygopro-pre-script/commit/99e4d0e0287833ac7940cd08a1b128c3c76d5e73 created.
But, if player would be used Tatsunoko by Synchro Material, Glyongandr doesn't work properly...

**Comment by mercury233** [comment]
OK, good job!
