### ISSUE TITLE
Equip Spell and negate effect issue

### ISSUE THREAD

**Issue by MichaelLawrenceDee** [Fluorohydride/ygopro-pre-script#58]
We just had a confirmation of rulings from Konami about Equip Spells and cards such as Imperial Order and Bujingi Turtle.

If an Equip Spell (not counting Normal Traps that turn into Equip Cards) is negated, it still equips to the monster instead of being sent to grave.

**Comment by mercury233** [comment]
I guess you want to report this issue in https://github.com/Fluorohydride/ygopro
