### ISSUE TITLE
Setcode for "Magician Girl" and "Celtic Guard"

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#6]
There isn't a setcode for `Magician Girl`, and I would like opinions about the `Celtic Guard` setcode, which is currently `0xe4`.

**Comment by destdev** [comment]
We have amorphages as 0xe0 as the last entry atm, thus I'd say, just continue with 0xe1 and 0xe2?

**Comment by EerieCode** [comment]
The code 0xe1 is already in use for the "Lunalight" cards: as for the others, "Magician Girl" is currently at 0xe3 and "Celtic Guard" at 0xe4. How about moving "Celtic Guard" to 0xe2 and continuing from 0xe4?

**Comment by Zayelion** [comment]
Nice seeing you here Eerie!

**Comment by destdev** [comment]
uh ... Lunalight is 0xdf, not 0xe1
if you have 0xe1 already occupied on your end something must be slightly off there, except for those 2 setcodes we don't have anything else that's missing

**Comment by EerieCode** [comment]
I was told the official setcode for "Lunalight" hadn't changed. Ok, just to
be sure, what are the current setcodes? From 0xda, at least. This way I'll
be able to correct all of them once I get back from work.

2016-01-20 10:29 GMT+01:00 dest <notifications@github.com>:

**Comment by destdev** [comment]
0xda Dracoverlord
0xdb Phantom-
0x10db The Phantom Knights
0xdc Super Quantum
0x10dc Super Quantum Mecha Pilot
0x20dc Super Quantum Mecha Beast
0xdd Blue-Eyes
0xde Exodia
0xdf Lunalight
0xe0 Amorphage

**Comment by Zayelion** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/blob/master/strings.conf Line 748
>0xda Dracoverlord
0xdb Phantom-
0x10db The Phantom Knights
0xdc Super Quantum
0x10dc Super Quantum Mecha Pilot
0x20dc Super Quantum Mecha Beast
0xdd Blue-Eyes
0xde Exodia
0xdf Lunalight
0xe0 Amorphage

**Comment by EerieCode** [comment]
Thank you! I'll begin to change the setcodes: how about putting them in the same order they were revealed, "Magician Girl" as 0xe1 and "Celtic Guard" as 0xe2? Is it okay for you?

**Comment by EerieCode** [comment]
I've just rewritten the beta cards with the official setcodes. For now "Magician Girl" is 0xe1 and "Celtic Guard" is 0xe2: if those are changed, let me know and I'll rewrite them as soon as I can.

**Comment by Zayelion** [comment]
You have commit rights to this repo so be sure to coordinate with us.

**Comment by StormWulf** [comment]
Destdev, do you agree with Eerie's proposed setcodes?

**Comment by destdev** [comment]
I do agree with those, yes
