### ISSUE TITLE
November 2016 VJump cards

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#65]
**Maximum Crisis**
- [x] MACR-JP009 - Predaplant Ophrys Scorpio --捕食植物オフリス・スコーピオ
- [x] MACR-JP010 - Predaplant Darling Cobra --捕食植物ダーリング・コブラ
- [x] MACR-JP011 - Predaplant Cordyceps --捕食植物コーディセップス
- [x] MACR-JP012 - Lyrical Luscinia - Cobalt Sparrow --LL-コバルト・スパロー
- [x] MACR-JP013 - Lyrical Luscinia - Sapphire Swallow --LL-サファイア・スワロー
- [x] MACR-JP014 - Lyrical Luscinia - Turquoise Warbler --LL-ターコイズ・ワーブラー
- [x] MACR-JP025 - True Draco Da’at Metatron, the Mechsoldier --真竜機兵ダースメタトロン
- [x] MACR-JP02? - True Draco Mariamune, the Phoenix --真竜凰マリアムネ
- [x] MACR-JP02? - True Draco Dynamite Knuckle, the Fighter --真竜機士ダイナマイトK
- [x] MACR-JP02? - True Draco Ignis Heat, the Warrior --真竜戦士イグニスH
- [x] MACR-JP02? - True Draco Majesty Maiden, the Mage --真竜導士マジェスティM
- [x] MACR-JP043 - Lyrical Luscinia - Assembly Nightingale --LL-アセンブリー・ナイチンゲール
- [x] MACR-JP046 - True King V.F.D., The Beast --真竜皇V.F.D.
- [x] MACR-JP052 - Transcendental Fusion --超越融合
- [x] MACR-JP0?? - True Draco Succession --真竜の継承
- [x] MACR-JP0?? - Dragonic Diagram --ドラゴニックD
- [x] MACR-JP0?? - Revival of the True King --真竜皇の復活
**Dimension Box**
- [x] DBLE-JP003 - The Phantom Knights of Mist Claws --幻影騎士団ミストクロウズ
- [x] DBLE-JP010 - Lunalight Kaleido Chick --月光彩雛
- [x] DBLE-JP015 - Lyrical Luscinia - Recite Starling --LL-リサイト・スターリング
- [x] DBLE-JP016 - Superheavy Samurai Daihachi --超重武者ダイ-8
- [x] DBLE-JP0?? - Predator Craft --捕食生成
**Premium Pack 19**
- [x] PP19-JP014 - Number 70: Deadly Sin --No.70デッドリー・シン
- [x] PP19-JP0?? - Brohunder --ONiサンダー
- [x] PP19-JP0?? - Frightfur Reknit --デストーイ・リニッチ
- [x] PP19-JP0?? - Darklord Ukobach --堕天使ユコバック
- [x] PP19-JP0?? - Gozuki --牛頭鬼
- [x] PP19-JP0?? - Necroid Synchro --ネクロイド・シンクロ
- [x] PP19-JP015 - Celestial Double Star Shaman --天輪の双星道士
**Pendulum Evolution**
- [x] SD31-JP001 - Astrograph Sorcerer --アストログラフ・マジシャン
- [x] SD31-JP002 - Chronograph Sorcerer --クロノグラフ・マジシャン
- [x] SD31-JP003 - Iris Magician --虹彩の魔術師
- [x] SD31-JP004 - Black Fang Magician --黒牙の魔術師
- [x] SD31-JP005 - White Wing Magician --白翼の魔術師
- [x] SD31-JP006 - Violet Poison Magician --紫毒の魔術師
- [x] SD31-JP023 - Pendulumgraph of Ages --星霜のペンデュラムグラフ
**20th Anniversary Pack**
- [] 20AP-JP0?? - Diabound Kernel --ディアバウンド・カーネル
- [] 20AP-JP0?? - Dark Summoning Beast --暗黒の召喚神
- [] 20AP-JP0?? - Fallen Paradise --失楽園

**Comment by EerieCode** [comment]
Since VJump decided to give us over 30 new cards this month, I thought it'd be best to keep a checklist so that we don't end up getting on each other's codes. Let's mark here which cards we're willing to do, ok? A few noteworthy issues for the archetypes:
- Maxut has just uploaded better pictures for the Structure Deck Sorcerers, and their effects clearly list as archetypes "Fusion Dragon", "Synchro Dragon", "Xyz Dragon" and "Pendulum Dragon" (also the monster "Supreme Dragon King Z-Arc" that is not part of the Deck, which is weird but unrelated to the issue). How do we deal with this? Should we make 0xf0 as a all-catch superarchetype, like for the Abyss Actors, and put them as, for instance, 0x10f0 for Pendulum, 0x20f0 for Fusion and so forth? Or do you have other ideas?
- Lyrical Luscinia is also a new archetype, but I think it can be set as 0x1f5 without many problems.
- While "True King" and "True Draco" are technically unrelated in English, it appears that originally "True Draco" was actually _Shinryuu_, while "True King" was _Shinryuuou_. Should we put them as 0x1f6 for "True Draco" and 0x10f6 for "True King"?

**Comment by DailyShana** [comment]
for 4 dragons, just treat them as normal archetypes, I think it is meaningless to consider "Dragon" as a archetypes.
"True King" is also "True Draco" cards, but it seems no cards refer to "True King" directly at present.

**Comment by EerieCode** [comment]
There is one, actually: the last effect of "[True King V.F.D., the Beast](http://yugioh.wikia.com/wiki/True_King_V.F.D.,_the_Beast)" refers explicitly to "True King" monsters.

**Comment by DailyShana** [comment]
that translation is wrong, it only refers to "True Draco"

**Comment by mercury233** [comment]
sorry but I don't think I can write any script until 20 hours later `_(:з」∠)_`

**Comment by EerieCode** [comment]
Well, I think with this we've done all the cards with complete effects. Good work, everyone!
Now the only ones missing are [Diabound Kernel](http://yugioh.wikia.com/wiki/Diabound_Kernel), [Dark Summoning Beast](http://yugioh.wikia.com/wiki/Dark_Summoning_Beast) and [Fallen Paradise](http://yugioh.wikia.com/wiki/Fallen_Paradise). The second one is missing a huge chunk of its effect, so it's probably a lost cause at the moment, but do you think the other two are feasable? Kernel is missing the last line of its effect, but given the position, I think it might simply be "This effect can be used during either player's turn", the typical way in the OCG to indicate a Quick Effect: Fallen Paradise, on the other hand, has no holes. What do you think?
