### ISSUE TITLE
Bug list for 18/11/16

### ISSUE THREAD

**Issue by BlackBallista** [Fluorohydride/ygopro-pre-script#68]
I'll be personally testing all the cards that were added today and informing of any issues with the scripts in this post. I'll make sure to update it as soon as the issues are found.

1) Lyrical Luscinia Turqoise Warbler (100912014) cant actvate her summon effect

![](http://i.imgur.com/Y5Apd9m.jpg)

**Comment by EerieCode** [comment]
Should be fixed now. Thank you very much!

**Comment by BlackBallista** [comment]
Lyrical Luscinia - Sapphire Swallow (100912014) cannot activate her effect to attach a material from the graveyard


![](http://i.imgur.com/yvlTY1B.png)

**Comment by EerieCode** [comment]
Fixed!

2016-11-18 17:00 GMT+01:00 BlackBallista <notifications@github.com>:

**Comment by BlackBallista** [comment]
Lyrical Luscina - Assembly Nithingale (100912043) cannot activate her effect to protect, in neither players turn

![](http://i.imgur.com/KmGryOo.jpg)

**Comment by EerieCode** [comment]
Try now: if it doesn't work after this, I'll fix it once I return home.

**Comment by BlackBallista** [comment]
all 3 reported bugs were fixed, good job eerie!

I'll continue testing and updating

**Comment by BlackBallista** [comment]
Predaplant Ophyris Scorpio(100912009) cannot activate its effect to special summon once the cost is paid

![](http://i.imgur.com/REV5tzZ.jpg)

**Comment by EerieCode** [comment]
It should be fine now

**Comment by BlackBallista** [comment]
Predaplant Ophyris Scorpio(100912009) did not give me the trigger to activate his effect when it was special summoned by Predaplant Cordyceps(100912011) . I suspect this to be an issue with Scorpio because Cordyceps itself worked as intended. No error text was presented 

Predaplant Darling Cobra (100912010) cannot activate its effect to search a "fusion" card. No error text was present

**Comment by EerieCode** [comment]
Darling should work now, though I'll have to look over the code once more later. I'm on a cellphone now, so I can't check the other issue properly: I'll work on it once I'm back home.

**Comment by BlackBallista** [comment]
Iris Magician (100331003) cannot activate his effect to double damage

![](http://i.imgur.com/mgijPtn.jpg)

**Comment by EerieCode** [comment]
A simple misspelling at that line: writing GetHandler instead of GetHandler
should be enough to fix it. I can't do it right now, but you can change it
in your script and test again to see if there's something else. Something
similar might happen with Black Fang, I C&P that section when I made the
script for the later: if so, it should be fixable in the exact same way.

Il 18 nov 2016 5:49 PM, "BlackBallista" <notifications@github.com> ha
scritto:

**Comment by BlackBallista** [comment]
Black Fang Magician (100331004) cannot activate his effect to reduce attack.

![](http://i.imgur.com/91kFEIT.jpg)

his effect to special summon however works correctly.

**Comment by EerieCode** [comment]
As I suspected: it's the same error as Iris Magician I mentioned before.

**Comment by destdev** [comment]
fixed iris and black fang
not sure about the predaplant bugs, I'll also look if I can find anything aside from the wrong card target properties ...

**Comment by destdev** [comment]
if you summon with Predaplant Cordyceps you can't normal or special summon anything except by fusion summon, that's why Scorpio didn't trigger there

**Comment by BlackBallista** [comment]
True King V.F.D, The Beast (100912046) can activate its effect multiple times per turn.

**Comment by destdev** [comment]
fixed

**Comment by BlackBallista** [comment]
Also, True King V.F.D, The Beast (100912046)'s effect to allow you to destoy opponents monsters doesnt seem to be working (Could it be related to the changed made to the other true kings? salvation has not implemented them yet)

**Comment by destdev** [comment]
if you don't have the change to the other true kings the effect will not work, you need those

**Comment by EerieCode** [comment]
It's possible. I'll test it later

**Comment by BlackBallista** [comment]
alright, will update them, thanks for letting me know

**Comment by BlackBallista** [comment]
Celestial Double Star Shaman (100214015) can only summon up to 2 level 2 monsters, when the maximum should be 4.

**Comment by destdev** [comment]
fixed that

**Comment by BlackBallista** [comment]
I would appreciate if someone could check Super Heavy Samurai Daihachi's (100212016) script to see if the effect to search is working correctly. It doesnt seem to be able to activate but that could be a problem of lack of targets due to the new superheavy samurai soul setcode not being implemented correctly

**Comment by BlackBallista** [comment]
Gozuki (100214017) cannot activate his effect to specials ummon from hand. No error text present

**Comment by BlackBallista** [comment]
Trascendant Polymerization (100912052) cannot be activated. No error text

![](http://i.imgur.com/Pfh9lAg.jpg)

**Comment by EerieCode** [comment]
You must use monsters on your field for the Fusion Summon.

**Comment by BlackBallista** [comment]
lol, sorry

**Comment by BlackBallista** [comment]
Trascendant Polymerization (100912052) cannot activate its effect to special summon from grave. No red text Present

**Comment by EerieCode** [comment]
I can't see any obvious issue in the script. I'll have to test it tomorrow, it's too late to do it now.

**Comment by BlackBallista** [comment]
Pendulumgraph of ages (100331023) cannot be activated

![](http://i.imgur.com/xwSaQBY.jpg)

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/273ba679dca5750d7d868d71f58f7a29929bc6bb Fixed.

**Comment by EerieCode** [comment]
"Transcendental Polymerization" should be fine now. I've tested it, it worked without problems.

**Comment by EerieCode** [comment]
"Superheavy Samurai Daihachi" has also been fixed.

**Comment by mercury233** [comment]
why do _Pendulumgraph of Ages_ check if the cards are face-up after them leave field? as I know, there is no such limit for other similar cards.
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=19522&keyword=&tag=-1

**Comment by DiabladeZat** [comment]
There's an issue with "Pendulumgraph of Spacetime". When you use it's effect when first flipping the card face-up, it dosen't show the blinking animation that usually happens when you target a card. It does when you activate the effect after the card has already been flipped however. 

No animation:
https://www.youtube.com/watch?v=h0x3WJ-t2eQ&feature=youtu.be

Animation:
https://www.youtube.com/watch?v=aNuEY83fdnM&feature=youtu.be

**Comment by destdev** [comment]
uh ... is there a setting where an issue is not auto closed after putting a link into the commit?

**Comment by Zayelion** [comment]
No, use a different notation.

**Comment by mercury233** [comment]
so we should treat this list as finished.
