### ISSUE TITLE
Pre-release cards that get released

### ISSUE THREAD

**Issue by StormWulf** [Fluorohydride/ygopro-pre-script#7]
The cards from BOSH-EN and SHVI-JP in addition to Lunalight Crimson Fox has been added to ygopro-scripts a while ago. Since this repository is intended to focus on pre-release cards, those cards need to be addressed. Should they be deleted or archived? I'd like if someone keeps track when they're added to ygopro-scripts and make the decision if the cards added there are functional.

**Comment by mercury233** [comment]
Git and Github have history function, so I think we can just remove those scripts, after they are stable.

**Comment by StormWulf** [comment]
I'll let you and Destdev use your judgment to determine if those scripts are ready to go

**Comment by Zayelion** [comment]
Just as @mercury233 aid they should be removed once added to the main repository of ygopro-script.

**Comment by StormWulf** [comment]
Is it safe to say that the cards on the main repository are all staple?

**Comment by Zayelion** [comment]
The function of the repo is to hold cards that can not be added to the main scripts repo because they lack proper card ids, once they have the proper card id they should be placed in their proper place regardless of 'stability' or correctness.
