### ISSUE TITLE
Card bugs 12/8

### ISSUE THREAD

**Issue by BlackBallista** [Fluorohydride/ygopro-pre-script#75]
Performapal Ballad (100214001) has  a monster effect that should make the opponent monster lose attack equal to the attck of a performapal monster who attacked it. Instead, its adding that ammount of attack. Furthermore this attack addition doesnt end at the end of the turn like the attack reduction is supposed to

**Comment by BlackBallista** [comment]
Performapal Barracuda (100214002) cannot activate its monster effect during either player's turn.

**Comment by mercury233** [comment]
Both bugs were fixed. The atk down effect of _Performapal Ballad_ is infinite.
