### ISSUE TITLE
Requesting repo access

### ISSUE THREAD

**Issue by KoneSkirata** [Fluorohydride/ygopro-pre-script#8]
Hello anyone,
dunno where to post this, i hope it's okay here.
I'm requesting access to this repository (better late than never :D)

I'm working as a scripter for DevPro.

**Comment by mercury233** [comment]
@Fluorohydride BTW, I think @nekrozar should has access too.

**Comment by Zayelion** [comment]
I second @nekrozar, and Kone does work at Devpro and has worked there for a while its just that I think @KoneSkirata should be more active on github before we allow him to have commit access.

I think they should just do pull request for the moment till they have that record of good commits.

**Comment by StormWulf** [comment]
The issue that I have with giving access to @KoneSkirata is that DevPro doesn't use our ID convention. I don't mind a DevPro person collaborates in this repository, but DevPro should consider adapting our ID convention, as it will make their jobs easier.

**Comment by KoneSkirata** [comment]
The reason for DevPro not using our new convention is that i wasn't aware of it's application already :P Now that i know of this repo's existence have already changed that.

**Comment by nekrozar** [comment]
Sorry, I don't have access to this repository...
So I can't add some Jump Festival new cards...
Japanese Source: http://blog.livedoor.jp/maxut/archives/46798967.html
![7c631f29](https://cloud.githubusercontent.com/assets/10573786/12965694/7bc54dc8-d09b-11e5-8cce-388d6079259d.jpg)
![13121495](https://cloud.githubusercontent.com/assets/10573786/12965700/8520422e-d09b-11e5-908a-d8da9ce7bbb7.jpg)
Could you get me access to this repository?

**Comment by Zayelion** [comment]
We are petitioning @Fluorohydride on your behalf, but in the meantime pull request are accepted!

**Comment by nekrozar** [comment]
@Fluorohydride Thank you!
