### ISSUE TITLE
Should we make "Synchron" and "Synchro Dragon" belong to same setcode?

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro-pre-script#82]
```
!setname 0x17 Synchro	シンクロ
!setname 0x1017 Synchron	シンクロン
!setname 0x2017 Synchro Dragon	シンクロ・ドラゴン
```

**Comment by EerieCode** [comment]
Agreed: it's probably the best time to do it, if we do it after Pendulum Evolution is released we'd end up having to change a lot of card for later archetypes. And it would be nice to be consistent, give the other Summon methods got the same treatment.

**Comment by mercury233** [comment]
done
