### ISSUE TITLE
Possible issues with effects that activate Spell/Traps directly

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#84]
Some players on Percy have reported various problems with cards that activate Spell/Traps directly. I don't know if those issues are exclusive to that simulator or if they happen here too, but I thought it would be best to open an issue about them anyway. Said problems are:

- The effect of "Ignis Heat" and "Dynamite Knuckle" should allow the player to either add to their hand or activate a Spell/Trap card from the Deck when the opponent activates an effect. If this effect is applied during the Damage Step, however, the option to activate the cards doesn't appear: they can be only added to the hand. I'm not sure if that's an issue with the way these cards are scripted or if the problem is at the source, in the function Effect.IsActivatable().
- The effect of "Performapal Sky Magician" that activates a Continuous Spell doesn't fire the appropriate events at resolution. A user just reported that cards like "Spell Absorption" (51481927), whose Continuous effect should apply whenever a Spell card resolves, doesn't activate when a card is activated by Sky Magician. The same issue happens with Sky Magician's ATK increase effect: when I scripted the card I had to make it raise a special event manually and force the activation of the effect. As a reminder, the direct activation of a Spell card uses these lines of code:
`Duel.MoveToField(tc,tp,tp,LOCATION_SZONE,POS_FACEUP,true)			Duel.RaiseEvent(tc,EVENT_CHAIN_SOLVED,tc:GetActivateEffect(),0,tp,tp,Duel.GetCurrentChain())`

I don't know if these issues can be solved simply through scripting, or if we'll need to add to the core a different way to check and activate cards: in the meantime, I thought it'd be better to make an issue about it. What do you think?

**Comment by SharkYGOPRO** [comment]
Hi, You can create a script of the Supreme King Servant Dragon Dark Rebellion anime effect?
