### ISSUE TITLE
MACR scripting progress

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro-pre-script#88]
the usual list with a huge amount of card announcements^^

- [x] MACR-JP006 - Speedroid Vidroskull --ＳＲビードロドクロ
- [x] MACR-JP007 - Speedroid Fiendmagnet --ＳＲアクマグネ
- [x] MACR-JP030 - Zefratorah Grammaton --智天の神凰龍
- [x] MACR-JP032 - B.E.S. Big Core MK-3 --巨大戦艦ビッグコア ＭＫ３
- [x] MACR-JP035 - Fire Cracker --ファイヤークラッカー
- [x] MACR-JP036 - Haru Urara --灰流うらら
- [x] MACR-JP037 - Familiar-Possessed Lyna --憑依装着ライナ
- [x] MACR-JP038 - Fairy Tail - Kaguya --妖精伝姫- カグヤ
- [x] MACR-JP047 - Zoodiac Hammerkong --十二獣ハンマーコング
- [x] MACR-JP048 - Zoodiac Lyca --十二獣ライカ
- [x] MACR-JP059 - Spiral Wave of the Mythic Radiance Dragon --幻煌龍の螺旋波
- [x] MACR-JP060 - Digital Bug Signal --光虫信号
- [x] MACR-JP064 - Festival Spinning --盆回し
- [x] MACR-JP066 - The Phantom Knights of Lost Vambrace --	幻影騎士団ロスト・ヴァンブレイズ
- [x] MACR-JP071 - Zoodiac Xiangke --十二獣の相克
- [x] MACR-JP074 - Celestial Whirlpool of the Mythic Radiance Dragon --幻煌龍の天渦
- [x] MACR-JP079 - Eternal Nightmares --醒めない悪夢
- [x] MACR-JP080 - Diamond Duston --ダイヤモンドダストン

**Comment by nekrozar** [comment]
> http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=12921
> 「SRアクマグネ」の効果は１ターンに１度しか使用できない。
> **このカードはこのカードの効果によるS召喚でしかS素材にできない**。
> ①：このカードが自分メインフェイズに召喚・特殊召喚に成功した場合、相手フィールドの表側表示モンスター１体を対象として発動できる。
> そのモンスターとこのカードのみを素材として風属性Sモンスター１体をS召喚する。

_Speedroid Fiendmagnet_ has "Cannot be used as Synchro Material, except by its own effect."
So, I can't create _Speedroid Fiendmagnet_...
Do you have any good ideas?

**Comment by destdev** [comment]
I've stubled uppon another problem with that card. Could it be, that the "c:IsSynchroSummonable(nil,mg)" check fails if the target is on the opponents side unless that target has "EFFECT_SYNCHRO_MATERIAL" or something? At least my quick test setup (without the cannot be synchro material effect) fails at this point every time I test it... (Test Setup: this summoned + a normal level 4 none tuner monster (pendulum if that matters) + Chanbara)

I have an idea, however I don't know if it'll work that way, also that workaround most likely will have a small bug... I can't make or test it yet, I'll be away from now until (late?) evening today.
1. Make something along the line of Black Garden. Make a continuous effect that is called uppon Normal/Special summon and register some flag effect there. Make the card not being able to be synchro material unless it has that flag effect. Then answer a yes/no question if you intend to use the effect. If yes, raise a custom event (which should trigger the effect), if no remove the flag effect.
2. To avoid the issue described above (if that is an issue, and I didn't derp here?^^) make a continuous effect with EFFECT_SYNCHRO_MATERIAL for the opponents MZONE with that flag effect as condition.
3. To avoid another yes/no question you'd have to make the trigger a forced one instead of optioinal. Shouldn't make too much of a problem, however it might cause little bugs with the chain order if there is any. Also you have to remove the flag effect at the end here in case the card remains face up for some reason.

**Comment by EerieCode** [comment]
I'm trying to write the script for Fiendmagnet: it's going to be complicated, but it should work.

**Comment by destdev** [comment]
just arrived home now, thanks for executing that idea
as for possible bugs, as said, being a forced trigger instead of optional might screw up something if there are multiple chain links on the summon, also (without testing anything yet) I suspect one or another error if it is summoned mid chain perhaps?
Well, at least having this is better than nothing, maybe we can come up with solutions as bug reports are comming in... or maybe I'm just worried too much about maybes and I should just shut up until the card is actually tested^^
