### ISSUE TITLE
Kurikara the Immovable Avatar (101109031)

### ISSUE THREAD

**Issue by shadowfox87** [Fluorohydride/ygopro-pre-script#945]
The current script allows you to Normal Summon/Set from hand but the effect text says it cannot be Normal Summoned/Set.

`Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by Tributing all face-up monsters on the field that activated an effect in your opponent's Monster Zone this turn. Gains 1500 ATK for each monster Tributed for its Special Summon. During your End Phase: You can target 1 monster in your opponent's GY; Special Summon it to your field. You can only use this effect of "Kurikara the Immovable Avatar" once per turn.`

@mallu11

**Comment by mercury233** [comment]
In the current implement of "Special Summon Monster" in YGOPro, them should have `TYPE_SPSUMMON`(0x2000000) in their database.
